# -*- coding: utf-8 -*-
"""Seed data: Reinforcement Learning for manipulation."""

RL = [
    {
        "id": "ppo",
        "name": "PPO",
        "full_name": "Proximal Policy Optimization",
        "cat": "rl",
        "year": 2017, "month": 7,
        "orgs": ["openai"],
        "parents": [],
        "license": "code",
        "paper": "https://arxiv.org/abs/1707.06347",
        "tags": ["on-policy", "clipped objective", "workhorse"],
        "impact": 5,
        "confidence": "high",
        "tagline": "The clipped-objective policy gradient that made deep RL boring enough to actually use.",
        "summary": "PPO constrains each policy update with a clipped surrogate objective, capturing most of the stability of trust-region methods at a fraction of the implementation complexity. In robotics it became the default algorithm for massively parallel simulation training: locomotion, in-hand manipulation and sim-to-real dexterity pipelines almost all run PPO over thousands of parallel environments.",
        "innovation": [
            "Clipped surrogate objective giving trust-region-like stability with first-order optimization.",
            "Robust to hyperparameters across wildly different tasks, which is why it survived.",
        ],
        "matters": ["The algorithm actually running inside Isaac Lab, sim-to-real dexterity, and RLHF alike."],
        "limits": ["On-policy and therefore sample-hungry: impractical to run directly on real hardware."],
        "lineage": "Root of the on-policy branch used for sim-trained manipulation.",
    },
    {
        "id": "sac",
        "name": "SAC",
        "full_name": "Soft Actor-Critic",
        "cat": "rl",
        "year": 2018, "month": 1,
        "orgs": ["berkeley-rail"],
        "parents": [],
        "license": "code",
        "paper": "https://arxiv.org/abs/1801.01290",
        "tags": ["off-policy", "maximum entropy", "sample-efficient"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Maximum-entropy off-policy RL: sample-efficient enough to run on a real robot.",
        "summary": "SAC augments the reward with a policy-entropy term and learns off-policy from a replay buffer, giving both strong exploration and much better sample efficiency than on-policy methods. That combination made it the standard choice whenever RL has to touch physical hardware, and it remains the backbone of real-world manipulation RL systems such as SERL.",
        "innovation": [
            "Maximum-entropy objective producing robust, exploratory policies without hand-tuned noise schedules.",
            "Off-policy replay making real-robot training feasible in hours rather than weeks.",
        ],
        "matters": ["The algorithmic core of nearly every real-world robot RL result of the last several years."],
        "limits": ["Still needs a reward function and a reset mechanism, both hard to arrange in the real world."],
        "lineage": "Root of the off-policy branch used for real-robot manipulation RL.",
    },
    {
        "id": "qt-opt",
        "name": "QT-Opt",
        "cat": "rl",
        "year": 2018, "month": 6,
        "orgs": ["google-deepmind"],
        "parents": [],
        "license": "closed",
        "paper": "https://arxiv.org/abs/1806.10293",
        "tags": ["580k grasps", "7 robots", "closed-loop grasping"],
        "impact": 4,
        "confidence": "high",
        "tagline": "580,000 real grasp attempts across a robot farm, producing closed-loop grasping that learned to reposition and retry.",
        "summary": "QT-Opt is a scalable distributed Q-learning method using the cross-entropy method for continuous action selection, trained on 580k real grasp attempts collected over months by seven robots. It reached 96% success on unseen objects and, more interestingly, produced emergent behaviors nobody scripted: singulating cluttered objects, repositioning for a better grip, and retrying after failure.",
        "innovation": [
            "Distributed off-policy Q-learning at a data scale nobody had attempted on real hardware.",
            "Showed closed-loop RL grasping beats open-loop predict-then-execute pipelines.",
        ],
        "matters": ["The proof that real-robot RL scales with data, and the ancestor of Google's whole robot-learning program."],
        "limits": ["Enormous data cost for one task family; the robot farm was not reproducible outside Google."],
        "lineage": "Large-scale value-based RL, later fused with transformers in Q-Transformer.",
    },
    {
        "id": "dactyl",
        "name": "Dactyl",
        "full_name": "Learning Dexterous In-Hand Manipulation",
        "cat": "rl",
        "year": 2018, "month": 8,
        "orgs": ["openai"],
        "parents": ["ppo", "domain-randomization"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/1808.00177",
        "tags": ["Shadow Hand", "sim2real", "24 DoF"],
        "impact": 4,
        "confidence": "high",
        "tagline": "A 24-DoF hand reorienting a block, trained entirely in simulation and transferred with zero real-world data.",
        "summary": "Dactyl trained an LSTM policy with PPO across a massively randomized simulation, then deployed it on a Shadow Dexterous Hand to reorient a cube using vision and touch. It never saw the real world during training. The policy rediscovered human-recognizable grasp strategies such as finger pivoting and sliding, and the follow-up work solved a Rubik's cube one-handed with automatic domain randomization.",
        "innovation": [
            "Domain randomization at extreme scale as the sole sim-to-real mechanism.",
            "Recurrent policies that infer unobserved physical parameters online, an implicit system identification.",
        ],
        "matters": ["The canonical demonstration that dexterity can be learned in simulation and shipped to hardware."],
        "limits": ["Thousands of years of simulated experience for one narrow task; brittle outside the randomization distribution."],
        "lineage": "PPO plus domain randomization pushed to its limit on a high-DoF hand.",
    },
    {
        "id": "dextreme",
        "name": "DeXtreme",
        "cat": "rl",
        "year": 2022, "month": 10,
        "orgs": ["nvidia-gear"],
        "parents": ["dactyl", "isaac-gym"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2210.13702",
        "code": "https://github.com/NVlabs/DeXtreme",
        "tags": ["GPU sim", "ADR", "reproducible"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Dactyl-class in-hand dexterity reproduced on a single GPU workstation instead of a compute cluster.",
        "summary": "DeXtreme retrained cube reorientation on an Allegro Hand entirely inside GPU-accelerated Isaac Gym with automatic domain randomization, cutting the compute requirement from a large cluster to a handful of GPUs and open-sourcing the stack. It showed the sim-to-real dexterity result was a general recipe, not a one-off feat of OpenAI-scale engineering.",
        "innovation": [
            "End-to-end GPU simulation and training loop that made high-DoF dexterity affordable.",
            "Careful analysis of which randomizations actually matter for transfer.",
        ],
        "matters": ["Democratized sim-to-real dexterity research and validated GPU-parallel simulation as the standard tool."],
        "limits": ["Still a single narrow task, with reward shaping doing considerable hidden work."],
        "lineage": "Dactyl's approach re-implemented on Isaac Gym's massively parallel GPU simulator.",
    },
    {
        "id": "cql",
        "name": "CQL",
        "full_name": "Conservative Q-Learning",
        "cat": "rl",
        "year": 2020, "month": 6,
        "orgs": ["berkeley-rail"],
        "parents": ["sac"],
        "license": "code",
        "paper": "https://arxiv.org/abs/2006.04779",
        "tags": ["offline RL", "pessimism"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Learn from a fixed dataset without the Q-function hallucinating value for actions nobody ever tried.",
        "summary": "Offline RL fails because bootstrapped Q-values are wildly overestimated for out-of-distribution actions the dataset never contains. CQL adds a regularizer that pushes down Q-values for unseen actions while pushing up values for dataset actions, yielding a conservative lower bound on true value. It became the reference algorithm for extracting policies from logged robot data.",
        "innovation": [
            "Explicit pessimism about out-of-distribution actions as a principled fix for offline value overestimation.",
            "Made large static robot datasets usable for RL rather than only for imitation.",
        ],
        "matters": ["The bridge between the field's growing demonstration datasets and reward-driven improvement."],
        "limits": ["Conservatism costs performance when the dataset is broad; tuning the penalty is delicate."],
        "lineage": "A pessimistic variant of the off-policy actor-critic family SAC established.",
    },
    {
        "id": "rlpd",
        "name": "RLPD",
        "full_name": "RL with Prior Data",
        "cat": "rl",
        "year": 2023, "month": 2,
        "orgs": ["berkeley-rail"],
        "parents": ["sac", "cql"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2302.02948",
        "code": "https://github.com/ikostrikov/rlpd",
        "tags": ["sample efficiency", "50/50 sampling"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Skip offline pretraining entirely: just sample half your batch from prior data and half from online experience.",
        "summary": "RLPD showed that elaborate offline-to-online pipelines are largely unnecessary. Train off-policy from scratch, sample 50% of each minibatch from the prior dataset and 50% from fresh online interaction, add layer normalization and ensembling for stability, and you get faster and better results than pretrain-then-finetune schemes. Its simplicity made it the practical default for real-robot RL.",
        "innovation": [
            "Symmetric sampling between offline and online buffers as a complete substitute for offline pretraining.",
            "Identified layer normalization as the key stabilizer against value divergence.",
        ],
        "matters": ["The efficiency backbone under SERL and much subsequent real-world manipulation RL."],
        "limits": ["Assumes prior data is at least somewhat relevant to the target task."],
        "lineage": "A pragmatic simplification of offline-to-online RL built on SAC-style off-policy learning.",
    },
    {
        "id": "q-transformer",
        "name": "Q-Transformer",
        "cat": "rl",
        "year": 2023, "month": 9,
        "orgs": ["google-deepmind"],
        "parents": ["qt-opt", "rt-1"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2309.10150",
        "tags": ["per-dimension Q", "offline RL at scale"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Autoregressive Q-learning: treat each action dimension as a token and let a transformer do value-based RL at VLA scale.",
        "summary": "Q-Transformer discretizes each action dimension and predicts Q-values autoregressively per dimension, sidestepping the intractable maximization over high-dimensional continuous actions. Combined with a conservative regularizer and Monte Carlo returns, it trains on large mixed-quality robot datasets containing both expert demonstrations and failed autonomous rollouts, outperforming imitation baselines that must discard the failures.",
        "innovation": [
            "Per-dimension autoregressive Q-value prediction, making value-based RL compatible with transformer policies.",
            "Learns from failed data that imitation learning has to throw away.",
        ],
        "matters": ["Points at how large robot datasets full of mediocre trajectories can still improve a policy."],
        "limits": ["Closed; discretization and autoregressive value decoding are expensive at inference."],
        "lineage": "QT-Opt's value-based scaling re-expressed in RT-1's transformer token framework.",
    },
    {
        "id": "serl",
        "name": "SERL",
        "full_name": "Sample-Efficient Robotic Reinforcement Learning",
        "cat": "rl",
        "year": 2024, "month": 1,
        "orgs": ["berkeley-rail"],
        "parents": ["rlpd"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2401.16013",
        "code": "https://github.com/rail-berkeley/serl",
        "tags": ["real-world RL", "25-50 min training", "PCB insertion"],
        "impact": 4,
        "confidence": "high",
        "tagline": "A packaged software stack that trains real-robot manipulation policies from scratch in under an hour.",
        "summary": "SERL bundles an efficient off-policy learner, reward classifiers learned from a handful of images, automated resets and impedance control into one library. It trains policies for PCB insertion, cable routing and object relocation directly on hardware in 25 to 50 minutes, reaching near-perfect success and outperforming imitation baselines trained on comparable human time.",
        "innovation": [
            "Treated real-world RL as an engineering problem and solved the surrounding infrastructure, not just the algorithm.",
            "Learned image-based reward classifiers removing the need for hand-designed reward functions.",
            "Forward-backward controller pairs for automatic resets during unattended training.",
        ],
        "matters": ["Reframed real-world RL from research curiosity to something a lab can run before lunch."],
        "limits": ["Task-specific; each new task needs its own reward classifier and reset scheme."],
        "lineage": "RLPD's sample efficiency wrapped in production-grade real-robot infrastructure.",
    },
    {
        "id": "hil-serl",
        "name": "HIL-SERL",
        "full_name": "Human-in-the-Loop Sample-Efficient RL",
        "cat": "rl",
        "year": 2024, "month": 10,
        "orgs": ["berkeley-rail"],
        "parents": ["serl", "dagger"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2410.21845",
        "code": "https://github.com/rail-berkeley/hil-serl",
        "tags": ["100% success", "1-2.5 hours", "dynamic tasks"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Add a human who takes over when things go wrong, and RL reaches essentially perfect success on hard real tasks in a couple of hours.",
        "summary": "HIL-SERL combines vision-based RL with a human operator who intervenes via teleoperation when the policy is about to fail, feeding both demonstrations and corrections into the same off-policy learner. Across dynamic manipulation, precise assembly and dual-arm coordination it reports near-100% success within 1 to 2.5 hours of real training, with cycle times roughly twice as fast as the human demonstrations it learned from.",
        "innovation": [
            "Human interventions as an on-policy corrective data source inside an RL loop, uniting DAgger and RL.",
            "Demonstrated RL policies exceeding human teleoperation speed on real assembly tasks.",
        ],
        "matters": ["The strongest existing evidence that real-world RL, not just imitation, is deployable today."],
        "limits": ["Requires a skilled human present throughout training; scales poorly across many tasks."],
        "lineage": "SERL's stack with DAgger-style human corrections folded into the replay buffer.",
    },
    {
        "id": "eureka",
        "name": "Eureka",
        "cat": "rl",
        "year": 2023, "month": 10,
        "orgs": ["nvidia-gear", "ut-austin-rpl"],
        "parents": ["ppo"],
        "influences": ["code-as-policies"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2310.12931",
        "code": "https://github.com/eureka-research/Eureka",
        "tags": ["LLM reward design", "pen spinning", "evolutionary"],
        "impact": 3,
        "confidence": "high",
        "tagline": "An LLM writes the reward function, evaluates how training went, and rewrites it: superhuman reward engineering.",
        "summary": "Eureka has a coding LLM read the simulation environment source, generate candidate reward functions, train policies with them, and then mutate the rewards based on training statistics in an evolutionary loop. Across 29 environments it outperformed expert human-written rewards on 83% of tasks, and produced the first policy able to perform rapid pen-spinning tricks with a dexterous hand.",
        "innovation": [
            "Closed the loop between LLM code generation and RL training feedback for automated reward search.",
            "Reward reflection: feeding numeric training diagnostics back to the LLM as the mutation signal.",
        ],
        "matters": ["Attacks reward design, the most labor-intensive bottleneck in applying RL to manipulation."],
        "limits": ["Requires a simulator with readable source and cheap rollouts; does not transfer to real-world reward design."],
        "lineage": "LLM code generation applied to the reward-engineering step of a PPO training pipeline.",
    },
]
