# -*- coding: utf-8 -*-
"""Seed data: Representations, backbones, 3D scene encodings and action tokenizers."""

REP = [
    {
        "id": "transformer",
        "name": "Transformer",
        "full_name": "Attention Is All You Need",
        "cat": "rep",
        "year": 2017, "month": 6,
        "orgs": ["google-deepmind"],
        "parents": [],
        "license": "code",
        "paper": "https://arxiv.org/abs/1706.03762",
        "tags": ["attention", "foundation"],
        "impact": 5,
        "confidence": "high",
        "tagline": "The architecture underneath essentially every robot brain on this map.",
        "summary": "Self-attention replaced recurrence and convolution as the default sequence model. For robotics its properties matter twice over: it scales predictably with data and compute, it consumes heterogeneous token streams (images, language, proprioception, actions) in one sequence, and it enabled the language and vision foundation models that VLAs are built on.",
        "innovation": [
            "Self-attention as a general, parallelizable mechanism for modeling sequences of anything.",
            "Empirical scaling behavior that made 'more data plus more compute' a reliable strategy.",
        ],
        "matters": ["Robotics inherited the whole foundation-model stack because of this architecture."],
        "limits": ["Quadratic attention cost constrains long-horizon, high-frequency robot context windows."],
        "lineage": "The common root of the VLA, world-model and representation branches.",
    },
    {
        "id": "clip",
        "name": "CLIP",
        "full_name": "Contrastive Language-Image Pretraining",
        "cat": "rep",
        "year": 2021, "month": 2,
        "orgs": ["openai"],
        "parents": ["transformer"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2103.00020",
        "code": "https://github.com/openai/CLIP",
        "tags": ["open vocabulary", "image-text alignment"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Aligned images and text in one embedding space, which is how robots got open-vocabulary perception.",
        "summary": "CLIP trained image and text encoders contrastively on 400M web pairs, producing a shared embedding where arbitrary language can retrieve or classify visual content zero-shot. For manipulation this was the unlock for open-vocabulary object grounding: a robot could suddenly be told to pick up a noun it had never seen in robot data, and the perception stack would still find it.",
        "innovation": [
            "Contrastive image-text pretraining at web scale, yielding zero-shot transfer to unseen categories.",
            "A reusable joint embedding that downstream systems could condition on with no fine-tuning.",
        ],
        "matters": ["The visual-semantic substrate under SayCan, VoxPoser and most VLA vision encoders."],
        "limits": ["Weak at spatial relations, counting and fine-grained geometry, which is exactly what manipulation needs."],
        "lineage": "Transformer encoders trained contrastively; the semantic half of nearly every robot perception stack.",
    },
    {
        "id": "r3m",
        "name": "R3M",
        "full_name": "A Universal Visual Representation for Robot Manipulation",
        "cat": "rep",
        "year": 2022, "month": 3,
        "orgs": ["meta-fair", "stanford-svl"],
        "parents": ["ego4d"],
        "influences": ["clip"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2203.12601",
        "code": "https://github.com/facebookresearch/r3m",
        "tags": ["human video", "frozen encoder", "time-contrastive"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Pretrain a visual encoder on human video with time-contrastive objectives, then freeze it for robot policies.",
        "summary": "R3M pretrains a ResNet on large egocentric human video using time-contrastive learning (frames nearer in time embed nearer), video-language alignment and sparsity regularization. Frozen and handed to a behavior-cloning policy it beat ImageNet and CLIP features on manipulation, showing robot-relevant visual features should encode temporal progress and affordance rather than object category.",
        "innovation": [
            "Time-contrastive objective capturing task progress rather than static semantics.",
            "Established the frozen-pretrained-encoder paradigm for data-scarce robot learning.",
        ],
        "matters": ["Made human video a usable pretraining corpus for manipulation before VLAs existed."],
        "limits": ["Frozen features cap performance; end-to-end VLA training has largely superseded the recipe."],
        "lineage": "Visual pretraining for control, informing encoder choices in later policies.",
    },
    {
        "id": "peract",
        "name": "PerAct",
        "full_name": "Perceiver-Actor",
        "cat": "rep",
        "year": 2022, "month": 9,
        "orgs": ["uw", "nvidia-gear"],
        "parents": ["transformer"],
        "influences": ["rlbench"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2209.05451",
        "code": "https://github.com/peract/peract",
        "tags": ["voxel", "keyframe actions", "6-DoF"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Predict where to put the gripper in a 3D voxel grid instead of predicting joint deltas: a large sample-efficiency win.",
        "summary": "PerAct voxelizes the workspace and uses a Perceiver transformer to classify which voxel the gripper should move to next, along with rotation and gripper state. Because the action space is spatially grounded and the representation is 3D, the policy generalizes across viewpoints and learns multi-task behavior from a handful of demonstrations per task, in sharp contrast to dense continuous control.",
        "innovation": [
            "Manipulation as 3D spatial classification: detect the next keyframe pose.",
            "Perceiver latent bottleneck making high-resolution voxel input tractable.",
        ],
        "matters": ["Defined the 3D keyframe-policy branch that dominates RLBench-style benchmarks."],
        "limits": ["Keyframe abstraction cannot express continuous contact-rich or dynamic motion."],
        "lineage": "Transformer perception applied to a voxelized 3D action space.",
    },
    {
        "id": "rvt",
        "name": "RVT / RVT-2",
        "full_name": "Robotic View Transformer",
        "cat": "rep",
        "year": 2023, "month": 6,
        "orgs": ["nvidia-gear", "uw"],
        "parents": ["peract"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2306.14896",
        "code": "https://github.com/nvlabs/rvt",
        "tags": ["multi-view", "much faster training", "mm precision"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Replace the expensive voxel grid with re-rendered virtual views: far faster to train and more accurate.",
        "summary": "RVT reprojects the point cloud into several orthographic virtual camera views, runs a multi-view transformer attending across them, and back-projects predicted 2D heatmaps into a 3D action, avoiding voxel-grid cost entirely. RVT-2 adds a coarse-to-fine zoom stage reaching millimeter precision on tasks like plug insertion while training in a fraction of PerAct's time.",
        "innovation": [
            "Virtual multi-view rendering as a cheap substitute for explicit 3D voxel reasoning.",
            "Coarse-to-fine spatial refinement reaching millimeter precision.",
        ],
        "matters": ["Made 3D keyframe policies practical to train and a standard high-precision baseline."],
        "limits": ["Depends on good depth and calibration, and inherits PerAct's keyframe abstraction."],
        "lineage": "PerAct's spatial action prediction made efficient via multi-view rendering.",
    },
    {
        "id": "3d-diffuser-actor",
        "name": "3D Diffuser Actor",
        "cat": "rep",
        "year": 2024, "month": 2,
        "orgs": ["cmu-ri"],
        "parents": ["diffusion-policy", "peract"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2402.10885",
        "code": "https://github.com/nickgkan/3d_diffuser_actor",
        "tags": ["3D tokens", "SE(3) diffusion"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Marries 3D scene tokens with diffusion action generation, topping both RLBench and CALVIN.",
        "summary": "The model lifts 2D visual features into 3D scene tokens using depth, then runs a 3D relative-attention denoising transformer that diffuses end-effector poses in SE(3). Combining 3D grounding with the multimodality of diffusion, it set state of the art on RLBench and CALVIN at release.",
        "innovation": [
            "3D relative attention between scene tokens and the noisy action, giving translation-equivariant reasoning.",
            "Diffusion over SE(3) poses rather than joint-space deltas.",
        ],
        "matters": ["Showed the 3D-policy and generative-policy branches are complementary rather than competing."],
        "limits": ["Requires depth and is heavier than 2D policies at inference."],
        "lineage": "PerAct's 3D grounding fused with Diffusion Policy's generative action head.",
    },
    {
        "id": "fast-tokenizer",
        "name": "FAST action tokenizer",
        "full_name": "Frequency-space Action Sequence Tokenization",
        "cat": "rep",
        "year": 2025, "month": 1,
        "orgs": ["physical-intelligence"],
        "parents": ["pi-0"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2501.09747",
        "code": "https://huggingface.co/physical-intelligence/fast",
        "tags": ["DCT", "compression", "universal tokenizer"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Compress action chunks with a DCT before tokenizing, which makes autoregressive VLAs viable at high control rates.",
        "summary": "Naive per-dimension binning of high-frequency actions produces long, highly redundant token sequences that autoregressive VLAs learn poorly. FAST applies a discrete cosine transform to the action chunk and byte-pair-encodes the coefficients, yielding much shorter token strings. A universal tokenizer trained on a million trajectories works across robots off the shelf, letting an autoregressive pi-0-FAST match diffusion-based pi-0 with substantially less training compute.",
        "innovation": [
            "Frequency-domain compression of action sequences before discretization.",
            "A universal, robot-agnostic action tokenizer released for reuse.",
        ],
        "matters": ["Removed the main technical objection to autoregressive rather than diffusion VLAs."],
        "limits": ["Autoregressive decoding remains slower at inference than a single flow-matching pass."],
        "lineage": "An action representation designed for pi-0-class models, replacing uniform binning.",
    },
    {
        "id": "eagle-vlm",
        "name": "Eagle VLM backbones",
        "cat": "rep",
        "year": 2024, "month": 8,
        "orgs": ["nvidia-gear"],
        "parents": ["clip"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2408.15998",
        "tags": ["mixture of encoders", "backbone"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "The VLM backbones NVIDIA's robot models sit on: mixtures of vision encoders tuned for spatial detail.",
        "summary": "The Eagle line studies mixing multiple vision encoders (semantic, segmentation-oriented, high-resolution tiling) inside one VLM, finding complementary encoders substantially improve fine-grained spatial understanding, which is exactly what manipulation needs and what single-encoder VLMs lack. Eagle-family backbones underpin GR00T N1's System 2.",
        "innovation": ["Mixture-of-vision-encoders design preserving spatial detail alongside semantics."],
        "matters": ["Backbone choice is a large and under-discussed driver of VLA performance."],
        "limits": ["General-purpose VLM work whose robot-specific benefit is indirect."],
        "lineage": "CLIP-style vision-language pretraining specialized for spatially detailed perception.",
    },
]
