# -*- coding: utf-8 -*-
"""Seed data: real robot trajectory corpora, collection interfaces, data multipliers.

Distinct from seed_benchmarks.py, which holds the evaluation suites. The split matters:
these entries answer "what do we train on", benchmarks answer "how do we know it worked".
"""

DATA = [
    {
        "id": "open-x-embodiment",
        "name": "Open X-Embodiment",
        "cat": "data",
        "year": 2023, "month": 10,
        "orgs": ["google-deepmind", "berkeley-rail", "stanford-iris"],
        "parents": ["rt-1", "bridgedata-v2"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2310.08864",
        "code": "https://robotics-transformer-x.github.io/",
        "tags": ["1M+ episodes", "22 embodiments", "34 labs"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Thirty-four labs pooled their robot data into one corpus, and cross-embodiment pretraining became possible.",
        "summary": "Open X-Embodiment aggregates 60 existing datasets from 34 research labs into a single standardized format covering more than a million real robot trajectories across 22 embodiments and 500+ skills. The unglamorous work of format unification is what made every subsequent open generalist policy — Octo, OpenVLA, RDT-1B — trainable at all.",
        "innovation": [
            "A shared data schema that made heterogeneous robot datasets mutually trainable in one batch.",
            "Community coordination at a scale robotics had never previously achieved.",
        ],
        "matters": ["The ImageNet moment for manipulation: the common substrate the open field trains on."],
        "limits": [
            "Severely imbalanced across labs and robots, with inconsistent camera setups and language annotation quality.",
            "Overwhelmingly single-arm tabletop data, so bimanual and dexterous coverage is thin.",
        ],
        "lineage": "The pooling of RT-1, BridgeData and dozens of other lab datasets into one corpus.",
    },
    {
        "id": "bridgedata-v2",
        "name": "BridgeData V2",
        "cat": "data",
        "year": 2023, "month": 8,
        "orgs": ["berkeley-rail"],
        "parents": ["roboturk"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2308.12952",
        "code": "https://rail-berkeley.github.io/bridgedata/",
        "tags": ["60k trajectories", "24 environments", "WidowX"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The scrappy, diverse, low-cost dataset most open-policy research actually evaluates on.",
        "summary": "BridgeData V2 contains over 60,000 trajectories across 24 environments on inexpensive WidowX arms, deliberately emphasizing environmental and object diversity rather than a single polished setup. Because the hardware is cheap and widely replicated, it became the de facto shared evaluation platform for open generalist policies.",
        "innovation": [
            "Prioritized breadth of scenes and objects over demonstration polish or task count.",
            "Built on affordable hardware other labs could reproduce, enabling genuinely comparable evaluation.",
        ],
        "matters": ["One of the few settings where different labs' policies can be compared on a common physical platform."],
        "limits": ["Low-cost arms have limited precision and payload, and it is single-arm only."],
        "lineage": "A foundational component dataset of Open X-Embodiment.",
    },
    {
        "id": "droid",
        "name": "DROID",
        "full_name": "Distributed Robot Interaction Dataset",
        "cat": "data",
        "year": 2024, "month": 3,
        "orgs": ["stanford-iris", "berkeley-rail", "tri"],
        "parents": ["bridgedata-v2"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2403.12945",
        "code": "https://droid-dataset.github.io/",
        "tags": ["76k trajectories", "564 scenes", "13 institutions"],
        "impact": 4,
        "confidence": "high",
        "tagline": "One hardware setup, thirteen institutions, 564 real scenes: diversity by construction rather than by aggregation.",
        "summary": "DROID standardizes on a single Franka-based platform with identical cameras and deploys it across 13 institutions, collecting 76,000 trajectories in 564 distinct real scenes including homes, offices and kitchens. Fixing the hardware while varying the environment isolates scene diversity as the experimental variable, and policies co-trained with DROID show markedly better generalization.",
        "innovation": [
            "Standardized hardware across many institutions, removing embodiment confounds from a diverse dataset.",
            "Deliberate collection in real everyday environments rather than on lab benches.",
        ],
        "matters": ["Supplied the environmental diversity that later work identified as the key generalization driver."],
        "limits": ["Single-arm Franka only, and teleoperation quality varies across sites."],
        "lineage": "BridgeData's diversity philosophy executed with standardized hardware at multi-institution scale.",
    },
    {
        "id": "roboturk",
        "name": "RoboTurk",
        "cat": "data",
        "year": 2018, "month": 11,
        "orgs": ["stanford-svl"],
        "parents": [],
        "license": "open",
        "paper": "https://arxiv.org/abs/1811.02790",
        "site": "https://roboturk.stanford.edu/",
        "tags": ["crowdsourced teleop", "smartphone controller"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Crowdsource teleoperation through a phone browser and collect in days what a lab collects in months.",
        "summary": "RoboTurk let remote users teleoperate robots through a smartphone acting as a 6-DoF controller, with low-latency video streamed back, gathering thousands of demonstrations across tasks in a matter of days from non-expert crowds. It was the first serious attempt to treat manipulation demonstrations as a crowdsourceable resource rather than something only a lab's own operators could produce.",
        "innovation": [
            "Phone-as-6-DoF-controller with a latency-tolerant streaming design, removing the specialized-hardware requirement.",
            "A crowdsourcing pipeline with quality filtering for demonstration data.",
        ],
        "matters": ["Established demonstration collection as a scaling problem to be engineered — the idea running through UMI, DROID and LeRobot."],
        "limits": ["Largely simulation-based, and non-expert demonstrations are noisy and uneven in quality."],
        "lineage": "The earliest attempt to scale demonstration collection beyond one lab's operators.",
    },
    {
        "id": "lerobot",
        "name": "LeRobot",
        "cat": "data",
        "year": 2024, "month": 5,
        "orgs": ["huggingface"],
        "parents": ["open-x-embodiment"],
        "license": "open",
        "code": "https://github.com/huggingface/lerobot",
        "site": "https://huggingface.co/lerobot",
        "tags": ["framework", "dataset format", "cheap hardware"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The Hugging Face of robotics: one dataset format, reference policy implementations, and arms that cost a few hundred dollars.",
        "summary": "LeRobot provides a standard dataset format with streaming and versioning, clean reimplementations of ACT, Diffusion Policy, pi-0, SmolVLA and others, a simulation and evaluation harness, and open hardware designs for very low-cost arms. It functions as the community's shared infrastructure layer and hosts thousands of user-contributed datasets.",
        "innovation": [
            "A versioned, streamable dataset format that made robot data as shareable as NLP datasets.",
            "Coupled cheap open hardware with the software stack, closing the loop for small-lab and hobbyist contribution.",
        ],
        "matters": ["The main on-ramp into the field, and the source of the community data SmolVLA trained on."],
        "limits": ["Community data quality is highly variable, and reimplementations can drift from the original papers."],
        "lineage": "Open X-Embodiment's standardization impulse turned into maintained community infrastructure.",
    },
    {
        "id": "mimicgen",
        "name": "MimicGen",
        "cat": "data",
        "year": 2023, "month": 10,
        "orgs": ["nvidia-gear", "ut-austin-rpl"],
        "parents": ["robomimic"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2310.17596",
        "code": "https://github.com/NVlabs/mimicgen",
        "tags": ["200 demos to 50k", "object-centric", "synthetic"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Turn 200 human demonstrations into 50,000 by replaying object-centric segments at new object poses.",
        "summary": "MimicGen decomposes a small set of human demonstrations into object-centric motion segments, then transforms and stitches those segments to synthesize demonstrations for new object placements, new objects and new scene configurations, keeping only replays that actually succeed. Roughly 200 source demonstrations expand into 50,000 usable ones, and policies trained on the synthetic set approach those trained on equivalent volumes of human data.",
        "innovation": [
            "Object-centric segmentation and spatial transformation of demonstrations as a data multiplier.",
            "Success-filtered replay, so only physically valid synthetic trajectories survive into the dataset.",
        ],
        "matters": ["A third answer to the data bottleneck, needing neither human video nor more teleoperation hours."],
        "limits": [
            "Generalizes over spatial arrangement, not over strategy — it cannot invent a new way to do the task.",
            "Requires known object poses and a simulator to validate the replays.",
        ],
        "lineage": "robomimic's demonstration infrastructure turned into a generative data engine.",
    },
    {
        "id": "agibot-world",
        "name": "AgiBot World",
        "cat": "data",
        "year": 2025, "month": 3,
        "orgs": ["agibot", "shanghai-ai-lab"],
        "parents": ["open-x-embodiment"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2503.06669",
        "code": "https://github.com/OpenDriveLab/AgiBot-World",
        "tags": ["1M+ trajectories", "bimanual", "dexterous hands"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "A million-plus bimanual trajectories collected on a purpose-built humanoid fleet in staged real environments.",
        "summary": "AgiBot World is a large-scale dataset collected on AgiBot's own hardware with dual arms, dexterous hands and whole-body mobility, recorded in purpose-built domestic and retail environments. Unlike aggregated corpora it is uniform in embodiment and rich in long-horizon bimanual tasks, addressing the thin dexterity coverage of most open datasets.",
        "innovation": [
            "Industrial-scale collection on a uniform bimanual humanoid platform, with tactile and dexterous-hand data.",
            "Staged realistic environments rather than lab benches.",
        ],
        "matters": ["One of the largest open sources of the bimanual dexterous data the field most lacks."],
        "limits": ["Tied to one proprietary embodiment, and scripted staging may limit true environmental variety."],
        "lineage": "The Open X-Embodiment pooling idea replaced by single-platform industrial-scale collection.",
    },
]
