# -*- coding: utf-8 -*-
"""Seed data: physics engines, parallel simulation and sim-to-real transfer."""

SIM = [
    {
        "id": "mujoco",
        "name": "MuJoCo",
        "full_name": "Multi-Joint dynamics with Contact",
        "cat": "sim",
        "year": 2012, "month": 10,
        "orgs": ["uw", "google-deepmind"],
        "parents": [],
        "license": "open",
        "code": "https://github.com/google-deepmind/mujoco",
        "site": "https://mujoco.org/",
        "tags": ["contact dynamics", "open-sourced 2021"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The contact simulator that made continuous-control research possible, later acquired by DeepMind and released free.",
        "summary": "Emo Todorov's MuJoCo solved soft contact dynamics accurately and fast enough for optimization-based control and reinforcement learning, becoming the substrate for essentially all continuous-control benchmarks. DeepMind acquired it and open-sourced it in 2021, later adding a GPU-accelerated version for massively parallel training.",
        "innovation": [
            "A convex contact formulation that is both physically reasonable and fast enough to sit inside a learning loop.",
            "Analytically tractable dynamics enabling gradient-based and optimal-control methods.",
        ],
        "matters": ["Nearly every RL manipulation result of the last decade was developed on it."],
        "limits": ["The contact model is an approximation, and deformables and fluids remain weak."],
        "lineage": "The root of the modern manipulation simulation stack.",
    },
    {
        "id": "domain-randomization",
        "name": "Domain Randomization",
        "cat": "sim",
        "year": 2017, "month": 3,
        "orgs": ["openai", "uw"],
        "parents": [],
        "license": "code",
        "paper": "https://arxiv.org/abs/1703.06907",
        "tags": ["sim2real", "randomize textures and physics", "ADR"],
        "impact": 4,
        "confidence": "high",
        "tagline": "If the simulator is varied enough, reality looks like just another random sample.",
        "summary": "Rather than trying to make simulation photorealistic, randomize textures, lighting, camera pose, object properties and physical parameters so widely that the policy must become invariant to them — at which point the real world falls inside the training distribution. This single idea underlies most successful sim-to-real transfer in manipulation.",
        "innovation": [
            "Reframed the sim-to-real gap as a generalization problem solvable by variation rather than by fidelity.",
            "Automatic curricula that expand randomization ranges as the policy improves.",
        ],
        "matters": ["The enabling technique behind Dactyl, DeXtreme and most sim-trained dexterity."],
        "limits": ["Excessive randomization yields conservative, low-performance policies; the ranges need careful tuning."],
        "lineage": "The methodological root of sim-to-real transfer.",
    },
    {
        "id": "robosuite",
        "name": "robosuite",
        "cat": "sim",
        "year": 2020, "month": 9,
        "orgs": ["ut-austin-rpl", "stanford-svl"],
        "parents": ["mujoco"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2009.12293",
        "code": "https://github.com/ARISE-Initiative/robosuite",
        "tags": ["modular", "standard controllers", "MuJoCo-based"],
        "impact": 3,
        "confidence": "high",
        "tagline": "The modular MuJoCo framework most academic manipulation benchmarks are built on top of.",
        "summary": "robosuite provides standardized robot models, controllers, task definitions and teleoperation interfaces over MuJoCo, designed so environments, robots and controllers can be recombined freely. Its real influence is as infrastructure: robomimic, RoboCasa and many other benchmarks are built on it.",
        "innovation": [
            "Clean separation of robot, controller, task and observation modality, enabling genuinely controlled comparisons.",
            "Standard controller implementations — operational space, joint impedance — that removed a common hidden confound.",
        ],
        "matters": ["The quiet foundation under a large share of academic manipulation research."],
        "limits": ["Inherits MuJoCo's contact approximations, and is not designed for photorealism."],
        "lineage": "A modular research framework layered on MuJoCo, feeding the benchmark lineage.",
    },
    {
        "id": "isaac-gym",
        "name": "Isaac Gym / Isaac Lab",
        "cat": "sim",
        "year": 2021, "month": 8,
        "orgs": ["nvidia-gear"],
        "parents": ["mujoco"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2108.10470",
        "code": "https://github.com/isaac-sim/IsaacLab",
        "tags": ["GPU physics", "thousands of parallel envs"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Run physics and the neural network on the same GPU with thousands of environments in parallel; training times fell by orders of magnitude.",
        "summary": "Isaac Gym keeps simulation state entirely on the GPU, eliminating CPU-GPU transfer and enabling thousands of parallel environments on a single card. Tasks that previously needed a CPU cluster train in minutes to hours on one workstation. Isaac Lab is the current successor built on Isaac Sim, and it underpins NVIDIA's humanoid and manipulation model training.",
        "innovation": [
            "An end-to-end GPU pipeline for physics, observation and policy update with no host round-trip.",
            "Made massively parallel PPO the standard recipe for sim-trained robot control.",
        ],
        "matters": ["The compute substrate behind most modern sim-to-real dexterity and humanoid work."],
        "limits": ["Contact fidelity trades off against speed, and it is tightly coupled to NVIDIA hardware."],
        "lineage": "MuJoCo-era simulation reimplemented for massively parallel GPU execution.",
    },
    {
        "id": "maniskill",
        "name": "ManiSkill / SAPIEN",
        "cat": "sim",
        "year": 2021, "month": 7,
        "orgs": ["ucsd-su"],
        "parents": ["mujoco"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2410.00425",
        "code": "https://github.com/haosulab/ManiSkill",
        "tags": ["GPU parallel", "articulated objects", "open challenge"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Open GPU-parallel manipulation simulation with strong articulated-object support and a long-running benchmark challenge.",
        "summary": "Built on the SAPIEN engine, ManiSkill provides GPU-parallelized simulation and rendering for manipulation, with particular emphasis on articulated objects — drawers, cabinets, faucets — and generalizable object-level skills. Its successive versions have run public challenges that shaped how the community measures generalization to unseen object instances.",
        "innovation": [
            "GPU-parallel rendering as well as physics, allowing vision-based RL at high throughput.",
            "A focus on articulated and category-level object generalization rather than fixed rigid objects.",
        ],
        "matters": ["The main fully open alternative to NVIDIA's stack for large-scale manipulation training, and the base SIMPLER builds on."],
        "limits": ["A smaller asset ecosystem than commercial simulators, and less established sim-to-real evidence."],
        "lineage": "Open academic GPU simulation for manipulation, developed in parallel with the Isaac line.",
    },
]
