# -*- coding: utf-8 -*-
"""Seed data: research labs & companies working on robot manipulation brains.

`priority` drives the update crawl order (see UPDATING.md):
  1 = frontier, check weekly    2 = active, check monthly    3 = check quarterly
"""

CATEGORIES = [
    {
        "id": "vla",
        "name": "Vision-Language-Action",
        "short": "VLA",
        "color": "#00e5ff",
        "blurb": "End-to-end models that map camera images + a language instruction directly to robot actions, usually built on a pretrained VLM backbone.",
    },
    {
        "id": "il",
        "name": "Imitation Learning & Policies",
        "short": "IL",
        "color": "#7c5cff",
        "blurb": "Learning manipulation from human demonstrations: behavior cloning, action chunking, diffusion and flow-matching policies.",
    },
    {
        "id": "rl",
        "name": "Reinforcement Learning",
        "short": "RL",
        "color": "#ff4d8d",
        "blurb": "Policies improved from reward and interaction — online, offline, sim-to-real, and human-in-the-loop.",
    },
    {
        "id": "world-model",
        "name": "World Models & Dreaming",
        "short": "WM",
        "color": "#ffb300",
        "blurb": "Learned predictive models of the environment used for planning or for training policies inside imagination.",
    },
    {
        "id": "vlm",
        "name": "VLM / LLM Planning & Grounding",
        "short": "VLM",
        "color": "#3dffab",
        "blurb": "Using foundation models as the high-level reasoner: task decomposition, affordance grounding, code generation, keypoint selection.",
    },
    {
        "id": "rep",
        "name": "Representations & Architectures",
        "short": "REP",
        "color": "#ff7a45",
        "blurb": "The substrate: backbone architectures, visual pretraining, 3D scene representations and action tokenizers.",
    },
    {
        "id": "data",
        "name": "Robot Datasets & Collection",
        "short": "DATA",
        "color": "#00b3ff",
        "blurb": "The fuel: large-scale real robot trajectory corpora, the interfaces used to collect them, and the methods that multiply a few demonstrations into many.",
    },
    {
        "id": "bench",
        "name": "Benchmarks & Evaluation",
        "short": "BENCH",
        "color": "#f0abfc",
        "blurb": "The yardstick: simulated task suites, evaluation protocols, and the studies that check whether reported gains survive contact with statistics.",
    },
    {
        "id": "human-data",
        "name": "Human Data & Egocentric Video",
        "short": "HUMAN",
        "color": "#a3e635",
        "blurb": "Learning manipulation from people rather than robots: egocentric video, wearable capture, hand tracking, and the latent-action and co-training methods that convert action-free human footage into robot supervision.",
    },
    {
        "id": "sim",
        "name": "Simulation & Sim2Real",
        "short": "SIM",
        "color": "#a0a8c0",
        "blurb": "Physics engines, massively parallel simulation, and the randomization tricks that let sim-trained policies survive reality.",
    },
]

LABS = [
    # ---------------------------------------------------------------- industry
    {
        "id": "google-deepmind",
        "name": "Google DeepMind — Robotics",
        "type": "industry",
        "country": "US / UK",
        "priority": 1,
        "focus": ["vla", "world-model", "vlm", "rl"],
        "notes": "Absorbed Google Brain Robotics & Everyday Robots. Origin of the RT-* line, SayCan, PaLM-E, Gemini Robotics, the Dreamer and Genie lines.",
        "sources": {
            "blog": "https://deepmind.google/discover/blog/",
            "site": "https://deepmind.google/",
            "github": "https://github.com/google-deepmind",
        },
    },
    {
        "id": "physical-intelligence",
        "name": "Physical Intelligence (π)",
        "type": "industry",
        "country": "US",
        "priority": 1,
        "focus": ["vla", "il", "rl"],
        "notes": "Founded 2024 by Levine, Hausman, Finn et al. Flow-matching VLAs (π0 line), the openpi release, FAST action tokenizer.",
        "sources": {
            "blog": "https://www.physicalintelligence.company/blog",
            "site": "https://www.physicalintelligence.company/",
            "github": "https://github.com/Physical-Intelligence/openpi",
        },
    },
    {
        "id": "nvidia-gear",
        "name": "NVIDIA GEAR Lab / Robotics",
        "type": "industry",
        "country": "US",
        "priority": 1,
        "focus": ["vla", "sim", "rl", "world-model"],
        "notes": "GR00T humanoid foundation models, Isaac Lab / Isaac Sim, Cosmos world foundation models, Eureka reward design.",
        "sources": {
            "blog": "https://blogs.nvidia.com/blog/category/robotics/",
            "site": "https://research.nvidia.com/labs/gear/",
            "github": "https://github.com/NVIDIA/Isaac-GR00T",
        },
    },
    {
        "id": "berkeley-rail",
        "name": "UC Berkeley — RAIL (Sergey Levine)",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["rl", "vla", "il", "world-model"],
        "notes": "SAC, Octo, BridgeData, SERL/HIL-SERL, DayDreamer, embodied chain-of-thought. The single densest source of robot-RL methodology.",
        "sources": {
            "site": "https://rail.eecs.berkeley.edu/",
            "blog": "https://bair.berkeley.edu/blog/",
            "github": "https://github.com/rail-berkeley",
        },
    },
    {
        "id": "stanford-iris",
        "name": "Stanford IRIS (Chelsea Finn)",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["il", "vla"],
        "notes": "ALOHA / ACT, Mobile ALOHA, OpenVLA co-author, meta-learning roots. Tightly coupled to Physical Intelligence.",
        "sources": {
            "site": "https://irislab.stanford.edu/",
            "github": "https://github.com/tonyzhaozh",
        },
    },
    {
        "id": "stanford-svl",
        "name": "Stanford Vision & Learning Lab (Fei-Fei Li, Jiajun Wu)",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["vlm", "bench", "data", "sim"],
        "notes": "VoxPoser, ReKep, BEHAVIOR benchmark suite. Zero-shot manipulation via foundation-model grounding.",
        "sources": {
            "site": "https://svl.stanford.edu/",
            "github": "https://github.com/StanfordVL",
        },
    },
    {
        "id": "stanford-realab",
        "name": "Stanford REALab (Shuran Song)",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["il", "data"],
        "notes": "Diffusion Policy and UMI originated with this group (formerly Columbia CAIR). Focus on scalable data collection hardware.",
        "sources": {
            "site": "https://real.stanford.edu/",
            "github": "https://github.com/real-stanford",
        },
    },
    {
        "id": "figure-ai",
        "name": "Figure AI",
        "type": "industry",
        "country": "US",
        "priority": 1,
        "focus": ["vla"],
        "notes": "Helix dual-system (S1/S2) humanoid VLA. Closed-source; announcements come via blog/video rather than papers.",
        "sources": {
            "blog": "https://www.figure.ai/news",
            "site": "https://www.figure.ai/",
        },
    },
    {
        "id": "tesla-optimus",
        "name": "Tesla — Optimus",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["il", "vla"],
        "notes": "End-to-end video-to-action policies reusing FSD infrastructure. No papers; track AI Day / earnings demos.",
        "sources": {"site": "https://www.tesla.com/AI"},
    },
    {
        "id": "tri",
        "name": "Toyota Research Institute — Robotics",
        "type": "industry",
        "country": "US",
        "priority": 1,
        "focus": ["il", "vla"],
        "notes": "Co-developer of Diffusion Policy; Large Behavior Models (LBM) program with rigorous statistical evaluation.",
        "sources": {
            "blog": "https://www.tri.global/news",
            "site": "https://www.tri.global/research/robotics",
            "github": "https://github.com/ToyotaResearchInstitute",
        },
    },
    {
        "id": "meta-fair",
        "name": "Meta FAIR — Embodied AI",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["world-model", "rep", "sim", "human-data"],
        "notes": "V-JEPA line, Habitat simulator, DINOv2/v3 backbones widely reused as robot visual encoders. "
                 "Also the origin of Ego4D, Ego-Exo4D and Project Aria — the capture stack most human-data robotics runs on.",
        "sources": {
            "blog": "https://ai.meta.com/blog/",
            "github": "https://github.com/facebookresearch",
        },
    },
    {
        "id": "openai",
        "name": "OpenAI",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["rl", "rep"],
        "notes": "Dactyl / ADR era defined sim-to-real dexterity; robotics team disbanded 2021 and restarted ~2024. PPO and CLIP remain load-bearing everywhere.",
        "sources": {"blog": "https://openai.com/news/", "github": "https://github.com/openai"},
    },
    {
        "id": "bytedance-seed",
        "name": "ByteDance Seed / Research",
        "type": "industry",
        "country": "CN",
        "priority": 2,
        "focus": ["vla", "world-model"],
        "notes": "GR-1 / GR-2 video-pretrained manipulation policies; strong video-generation crossover.",
        "sources": {"site": "https://seed.bytedance.com/", "github": "https://github.com/bytedance"},
    },
    {
        "id": "skild-ai",
        "name": "Skild AI",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["vla", "rl"],
        "notes": "CMU spinout (Deepak Pathak, Abhinav Gupta) pursuing an omni-bodied 'robot brain' across embodiments.",
        "sources": {"site": "https://www.skild.ai/"},
    },
    {
        "id": "1x-technologies",
        "name": "1X Technologies",
        "type": "industry",
        "country": "NO / US",
        "priority": 2,
        "focus": ["world-model", "vla"],
        "notes": "NEO humanoid; published a learned world model used as an evaluator for policies.",
        "sources": {"blog": "https://www.1x.tech/discover", "site": "https://www.1x.tech/"},
    },
    {
        "id": "dyna-robotics",
        "name": "Dyna Robotics",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["vla", "rl", "human-data"],
        "notes": "DYNA-1 model targeting long-duration autonomous dexterous tasks at commercial reliability. "
                 "Also pursuing large-scale egocentric human-video data collection — confirm any scale claims "
                 "against their own posts before citing them.",
        "sources": {"blog": "https://www.dyna.co/research", "site": "https://www.dyna.co/"},
    },
    {
        "id": "generalist-ai",
        "name": "Generalist AI",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["vla"],
        "notes": "Founded by Pete Florence (ex-Google DeepMind); general-purpose dexterous manipulation foundation models.",
        "sources": {"site": "https://generalistai.com/"},
    },
    {
        "id": "rai-institute",
        "name": "RAI Institute (ex-Boston Dynamics AI Institute)",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["rl", "il"],
        "notes": "Marc Raibert's research institute; athletic intelligence and model-based + learned control.",
        "sources": {"site": "https://rai-inst.com/"},
    },
    {
        "id": "boston-dynamics",
        "name": "Boston Dynamics",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["il", "rl"],
        "notes": "Electric Atlas manipulation; partnership with Toyota Research Institute on large behavior models.",
        "sources": {"blog": "https://bostondynamics.com/blog/", "site": "https://bostondynamics.com/"},
    },
    {
        "id": "amazon-far",
        "name": "Amazon FAR (Frontier AI & Robotics)",
        "type": "industry",
        "country": "US",
        "priority": 2,
        "focus": ["vla", "il"],
        "notes": "Absorbed Covariant's founders and much of its team in 2024; warehouse-scale manipulation data.",
        "sources": {"site": "https://www.amazon.science/research-areas/robotics"},
    },
    {
        "id": "huggingface",
        "name": "Hugging Face — LeRobot",
        "type": "industry",
        "country": "FR / US",
        "priority": 1,
        "focus": ["data", "il", "vla"],
        "notes": "De-facto open-source hub: reimplementations of ACT/Diffusion Policy/π0, SmolVLA, standardized dataset format, cheap SO-100/SO-101 arms.",
        "sources": {
            "github": "https://github.com/huggingface/lerobot",
            "site": "https://huggingface.co/lerobot",
            "blog": "https://huggingface.co/blog",
        },
    },
    {
        "id": "ai2",
        "name": "Allen Institute for AI (PRIOR)",
        "type": "nonprofit",
        "country": "US",
        "priority": 2,
        "focus": ["vlm", "sim"],
        "notes": "Molmo VLM with pointing supervision — a common grounding front-end for manipulation. THOR/ProcTHOR simulators.",
        "sources": {"site": "https://prior.allenai.org/", "github": "https://github.com/allenai"},
    },
    {
        "id": "microsoft-research",
        "name": "Microsoft Research",
        "type": "industry",
        "country": "US / CN",
        "priority": 3,
        "focus": ["vla", "vlm"],
        "notes": "CogACT and Magma lines; strong VLM pretraining feeding into embodied agents.",
        "sources": {"site": "https://www.microsoft.com/en-us/research/", "github": "https://github.com/microsoft"},
    },
    {
        "id": "agibot",
        "name": "AgiBot / 智元机器人",
        "type": "industry",
        "country": "CN",
        "priority": 2,
        "focus": ["data", "vla"],
        "notes": "AgiBot World — one of the largest open real-robot manipulation datasets; GO-1 policy family.",
        "sources": {"site": "https://www.agibot.com/", "github": "https://github.com/OpenDriveLab/AgiBot-World"},
    },
    {
        "id": "unitree",
        "name": "Unitree Robotics",
        "type": "industry",
        "country": "CN",
        "priority": 3,
        "focus": ["rl", "sim"],
        "notes": "Hardware-first (G1/H1 humanoids, arms). Matters mainly as the cheap platform much open manipulation research now runs on.",
        "sources": {"site": "https://www.unitree.com/", "github": "https://github.com/unitreerobotics"},
    },
    {
        "id": "galbot",
        "name": "Galbot / 银河通用",
        "type": "industry",
        "country": "CN",
        "priority": 3,
        "focus": ["vla", "sim"],
        "notes": "PKU-affiliated; synthetic-data-heavy grasping and mobile manipulation (GraspVLA, GroceryVLM).",
        "sources": {"site": "https://www.galbot.com/"},
    },
    {
        "id": "x-square",
        "name": "X Square Robot / 自变量机器人",
        "type": "industry",
        "country": "CN",
        "priority": 3,
        "focus": ["vla"],
        "notes": "WALL-A / Wall-OSS end-to-end manipulation models with partial open-source releases.",
        "sources": {"site": "https://www.x2robot.com/"},
    },
    {
        "id": "shanghai-ai-lab",
        "name": "Shanghai AI Laboratory",
        "type": "academic",
        "country": "CN",
        "priority": 2,
        "focus": ["vla", "data"],
        "notes": "SpatialVLA, InternVL backbones, OpenDriveLab collaboration on AgiBot World.",
        "sources": {"site": "https://www.shlab.org.cn/", "github": "https://github.com/OpenGVLab"},
    },
    # ---------------------------------------------------------------- academic
    {
        "id": "cmu-ri",
        "name": "CMU Robotics Institute",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["il", "rep", "rl", "human-data"],
        "notes": "DAgger and the imitation-learning theory lineage; 3D Diffuser Actor; Pathak/Gupta labs on "
                 "scalable embodied learning and the WHIRL/VideoDex human-video-to-robot line.",
        "sources": {"site": "https://www.ri.cmu.edu/", "github": "https://github.com/cmu-mld"},
    },
    {
        "id": "mit-csail",
        "name": "MIT CSAIL / Improbable AI",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["il", "rl", "sim"],
        "notes": "Tedrake's group (Diffusion Policy co-author, Drake) and Pulkit Agrawal's Improbable AI on sim-to-real dexterity.",
        "sources": {"site": "https://www.csail.mit.edu/", "github": "https://github.com/Improbable-AI"},
    },
    {
        "id": "columbia-crl",
        "name": "Columbia — Creative Machines / CAIR",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["il"],
        "notes": "Birthplace of Diffusion Policy (Shuran Song's group before the Stanford move).",
        "sources": {"site": "https://www.cs.columbia.edu/robotics/"},
    },
    {
        "id": "ut-austin-rpl",
        "name": "UT Austin — Robot Perception & Learning (Yuke Zhu)",
        "type": "academic",
        "country": "US",
        "priority": 1,
        "focus": ["bench", "data", "il", "sim"],
        "notes": "robomimic, RoboCasa, LIBERO — the benchmark backbone of the field. Joint appointment with NVIDIA GEAR.",
        "sources": {"site": "https://rpl.cs.utexas.edu/", "github": "https://github.com/ARISE-Initiative"},
    },
    {
        "id": "ucsd-su",
        "name": "UC San Diego (Hao Su, Xiaolong Wang)",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["sim", "rl", "bench"],
        "notes": "ManiSkill / SAPIEN simulation stack; TD-MPC line; dexterous hand teleoperation and RL.",
        "sources": {"site": "https://cseweb.ucsd.edu/~haosu/", "github": "https://github.com/haosulab"},
    },
    {
        "id": "nyu-grail",
        "name": "NYU — GRAIL (Lerrel Pinto)",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["il", "rl", "human-data"],
        "notes": "Behavior Transformers / VQ-BeT, cheap in-the-wild data collection rigs, on-robot fine-tuning, "
                 "and the EgoZero line on training policies from human recordings with no robot data at all.",
        "sources": {"site": "https://www.lerrelpinto.com/", "github": "https://github.com/notmahi"},
    },
    {
        "id": "berkeley-autolab",
        "name": "UC Berkeley AUTOLab (Ken Goldberg)",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["il", "data"],
        "notes": "Dex-Net grasping lineage; long-running work on reliable industrial-grade manipulation and data-driven grasping.",
        "sources": {"site": "https://autolab.berkeley.edu/", "github": "https://github.com/BerkeleyAutomation"},
    },
    {
        "id": "uw",
        "name": "University of Washington (Dieter Fox, Personal Robotics)",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["rep", "vlm", "sim"],
        "notes": "PerAct, RoboPoint, MuJoCo's origin (Todorov). Deep two-way traffic with NVIDIA Seattle robotics.",
        "sources": {"site": "https://robotics.cs.washington.edu/"},
    },
    {
        "id": "tsinghua-air",
        "name": "Tsinghua University (AIR / TSAIL)",
        "type": "academic",
        "country": "CN",
        "priority": 2,
        "focus": ["vla", "il"],
        "notes": "RDT-1B bimanual diffusion transformer; strong diffusion-model theory group feeding robot policies.",
        "sources": {"site": "https://air.tsinghua.edu.cn/en/", "github": "https://github.com/thu-ml"},
    },
    {
        "id": "pku",
        "name": "Peking University (CoRe / Hao Dong)",
        "type": "academic",
        "country": "CN",
        "priority": 3,
        "focus": ["vla", "sim"],
        "notes": "Embodied perception and dexterous manipulation; closely tied to Galbot.",
        "sources": {"site": "https://zsdonghao.github.io/"},
    },
    {
        "id": "georgia-tech",
        "name": "Georgia Tech (Danfei Xu, RIPL)",
        "type": "academic",
        "country": "US",
        "priority": 2,
        "focus": ["human-data", "il"],
        "notes": "EgoMimic and the wearable-capture line: treating human egocentric data as another embodiment "
                 "to co-train with, rather than something to retarget.",
        "sources": {
            "site": "https://faculty.cc.gatech.edu/~danfei/",
            "github": "https://github.com/SimarKareer",
        },
    },
    {
        "id": "apple",
        "name": "Apple — Machine Learning Research",
        "type": "industry",
        "country": "US",
        "priority": 3,
        "focus": ["human-data", "rep"],
        "notes": "EgoDex and related egocentric dexterous-manipulation datasets captured on head-mounted "
                 "consumer hardware with paired 3D hand pose.",
        "sources": {
            "site": "https://machinelearning.apple.com/",
            "github": "https://github.com/apple",
        },
    },
    {
        "id": "imperial-robot-learning",
        "name": "Imperial College London (Edward Johns)",
        "type": "academic",
        "country": "UK",
        "priority": 3,
        "focus": ["il", "bench"],
        "notes": "RLBench benchmark; one-shot imitation and coarse-to-fine manipulation.",
        "sources": {"site": "https://www.robot-learning.uk/"},
    },
    {
        "id": "freiburg",
        "name": "University of Freiburg (Abhinav Valada, Wolfram Burgard legacy)",
        "type": "academic",
        "country": "DE",
        "priority": 3,
        "focus": ["bench", "vla"],
        "notes": "CALVIN long-horizon language benchmark; HULC policies.",
        "sources": {"site": "http://rl.uni-freiburg.de/"},
    },
    {
        "id": "eth-rsl",
        "name": "ETH Zurich — Robotic Systems Lab",
        "type": "academic",
        "country": "CH",
        "priority": 3,
        "focus": ["rl", "sim"],
        "notes": "Massively-parallel RL and sim-to-real methodology (ANYmal); the techniques transfer directly to arms and hands.",
        "sources": {"site": "https://rsl.ethz.ch/", "github": "https://github.com/leggedrobotics"},
    },
    {
        "id": "tud-ias",
        "name": "TU Darmstadt — Intelligent Autonomous Systems (Jan Peters)",
        "type": "academic",
        "country": "DE",
        "priority": 3,
        "focus": ["rl", "il"],
        "notes": "Movement primitives, policy search, and the classical robot-learning foundations much of modern IL rests on.",
        "sources": {"site": "https://www.ias.informatik.tu-darmstadt.de/"},
    },
]
