# -*- coding: utf-8 -*-
"""Seed data: Vision-Language-Action models, part 2 (humanoids, open variants, reasoning)."""

VLA_2 = [
    {
        "id": "gemini-robotics",
        "name": "Gemini Robotics / Robotics-ER",
        "cat": "vla",
        "year": 2025, "month": 3,
        "orgs": ["google-deepmind"],
        "parents": ["rt-2"],
        "influences": ["palm-e"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2503.20020",
        "tags": ["Gemini 2.0", "embodied reasoning", "dexterity"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Gemini itself, taught to act, plus a sibling model whose only job is spatial and physical reasoning.",
        "summary": "Two coupled releases: Gemini Robotics-ER, a Gemini variant specialized for embodied reasoning (3D detection, pointing, grasp proposal, trajectory prediction), and Gemini Robotics, a VLA that adds action output on top. The pair demonstrated notably dexterous behaviors such as origami folding, card dealing and snack packing, with a cloud-hosted large model paired to an on-robot fast model to meet latency budgets.",
        "innovation": [
            "Separating embodied reasoning into its own callable model rather than baking it into one policy.",
            "Pointing and 3D-aware spatial prediction trained directly into a frontier VLM.",
            "Hybrid cloud/on-device inference split to reconcile model size with control rate.",
        ],
        "matters": ["Signals that frontier general-purpose models, not robotics-specific ones, may become the default robot brain."],
        "limits": ["Closed weights and restricted partner access; independent evaluation is not possible."],
        "lineage": "The RT-2 concept rebuilt on the Gemini family with a dedicated reasoning sibling.",
    },
    {
        "id": "gemini-robotics-15",
        "name": "Gemini Robotics 1.5 / ER 1.5",
        "cat": "vla",
        "year": 2025, "month": 9,
        "orgs": ["google-deepmind"],
        "parents": ["gemini-robotics"],
        "license": "closed",
        "site": "https://deepmind.google/discover/blog/",
        "tags": ["motion transfer", "thinking", "agentic tool use"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Thinks before acting, and moves skills between different robot bodies without retraining.",
        "summary": "An upgrade adding an explicit internal reasoning trace before action generation, and a motion-transfer mechanism letting skills learned on one embodiment (a bimanual ALOHA rig, say) run on another (a humanoid) with little or no new data. ER 1.5 was exposed to developers as an embodied-reasoning API able to call tools such as web search mid-task.",
        "innovation": [
            "Explicit think-then-act traces in a production VLA.",
            "Cross-embodiment motion transfer as a first-class capability rather than an emergent side effect.",
            "Agentic tool use inside the embodied reasoning loop.",
        ],
        "matters": ["Points toward one model serving a fleet of heterogeneous robots."],
        "limits": ["Closed; capability claims rest on vendor-run evaluations. Verify specifics before citing."],
        "lineage": "Iteration on Gemini Robotics with reasoning traces and embodiment transfer added.",
    },
    {
        "id": "groot-n1",
        "name": "GR00T N1",
        "cat": "vla",
        "year": 2025, "month": 3,
        "orgs": ["nvidia-gear"],
        "parents": ["pi-0", "eagle-vlm"],
        "influences": ["open-x-embodiment", "lapa", "ego4d"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2503.14734",
        "code": "https://github.com/NVIDIA/Isaac-GR00T",
        "tags": ["2B", "dual-system", "humanoid", "synthetic data"],
        "impact": 4,
        "confidence": "high",
        "tagline": "An openly released humanoid foundation model trained on a data pyramid of real, synthetic and human video.",
        "summary": "GR00T N1 couples a vision-language module (System 2, ~10 Hz) with a diffusion-transformer action module (System 1, up to 120 Hz), trained jointly end to end. Its distinguishing bet is the data pyramid: a small base of real teleoperation, a large layer of simulation and neurally generated trajectories, and a huge layer of egocentric human video, unified through learned latent actions so unlabeled video can still supervise the policy.",
        "innovation": [
            "Latent-action learning lets human video without action labels train a robot policy.",
            "Explicit dual-system architecture with different clock rates, trained end to end rather than stitched together.",
            "Open weights plus the synthetic-data pipeline and simulator that produced the training set.",
        ],
        "matters": ["The most complete open humanoid manipulation stack: model, data engine and simulator together."],
        "limits": ["Heavily tied to NVIDIA's simulation ecosystem; real-world evaluation breadth is narrower than pi-0's."],
        "lineage": "A pi-0-style VLM plus action expert, extended with latent actions and a synthetic data pipeline.",
    },
    {
        "id": "groot-n15",
        "name": "GR00T N1.5",
        "cat": "vla",
        "year": 2025, "month": 5,
        "orgs": ["nvidia-gear"],
        "parents": ["groot-n1"],
        "influences": ["cosmos"],
        "license": "open",
        "code": "https://github.com/NVIDIA/Isaac-GR00T",
        "tags": ["frozen VLM", "DreamGen"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Freeze the VLM to protect grounding, and let world-model-generated dream data carry new skills.",
        "summary": "An iteration on GR00T N1 that freezes the vision-language backbone during robot training to preserve grounding, improves the adapter between language and action, and folds in DreamGen: synthetic trajectories produced by video world models, teaching behaviors never demonstrated on hardware. Reported gains are largest in language following and few-shot adaptation to new embodiments.",
        "innovation": [
            "Freezing the VLM during post-training so robot data does not erode semantic grounding.",
            "Using video-world-model rollouts as a source of novel training trajectories.",
        ],
        "matters": ["An early production example of world-model-generated data training a deployed policy."],
        "limits": ["Incremental, and documented mostly through release notes rather than a standalone paper."],
        "lineage": "GR00T N1 with a frozen backbone and world-model-generated training data.",
    },
    {
        "id": "helix",
        "name": "Helix",
        "cat": "vla",
        "year": 2025, "month": 2,
        "orgs": ["figure-ai"],
        "parents": ["rt-2"],
        "influences": ["pi-0"],
        "license": "closed",
        "site": "https://www.figure.ai/news/helix",
        "tags": ["S1/S2", "35 DoF", "onboard", "multi-robot"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Full upper-body humanoid control at 200 Hz from onboard GPUs, with two robots collaborating under one model.",
        "summary": "Helix runs a 7B internet-pretrained VLM (S2) at 7-9 Hz producing a single latent vector, consumed by an 80M visuomotor transformer (S1) at 200 Hz that drives 35 upper-body degrees of freedom including individual fingers, wrists, head and torso. Both run on embedded GPUs in the robot. Figure demonstrated two Helix robots collaborating on grocery put-away with one set of weights and no task-specific fine-tuning.",
        "innovation": [
            "Decoupled S1/S2 running at different rates, communicating through one learned latent vector.",
            "Entirely onboard inference with no cloud dependency, at true servo rates.",
            "A single weight set controlling multiple cooperating robots.",
        ],
        "matters": ["Showed frontier-scale VLA behavior can fit inside a humanoid's power and latency budget."],
        "limits": ["No paper, no weights, no external evaluation; claims rest on company demonstrations."],
        "lineage": "The VLA concept restructured for embedded real-time humanoid control.",
    },
    {
        "id": "rdt-1b",
        "name": "RDT-1B",
        "full_name": "Robotics Diffusion Transformer",
        "cat": "vla",
        "year": 2024, "month": 10,
        "orgs": ["tsinghua-air"],
        "parents": ["diffusion-policy", "open-x-embodiment"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2410.07864",
        "code": "https://github.com/thu-ml/RoboticsDiffusionTransformer",
        "tags": ["1.2B", "bimanual", "unified action space"],
        "impact": 3,
        "confidence": "high",
        "tagline": "The largest open diffusion policy for bimanual manipulation, with an action space built to unify incompatible robots.",
        "summary": "RDT-1B scales diffusion transformers to 1.2B parameters, pretrains on over a million multi-robot episodes, and fine-tunes on a purpose-collected bimanual dataset. Its key device is a 128-dimensional physically interpretable unified action space where each slot has fixed physical meaning across robots, so one model can absorb single-arm, bimanual and differently configured platforms without discarding structure.",
        "innovation": [
            "Unified 128-D action space with fixed physical semantics per dimension for cross-embodiment pretraining.",
            "Scaling diffusion rather than autoregressive policies into the billion-parameter range.",
        ],
        "matters": ["One of the strongest fully open bimanual models, widely used as a base in Chinese robotics labs."],
        "limits": ["No language-model backbone at RT-2 scale, so semantic generalization is limited."],
        "lineage": "Diffusion Policy scaled up and given a cross-embodiment action representation.",
    },
    {
        "id": "cogact",
        "name": "CogACT",
        "cat": "vla",
        "year": 2024, "month": 11,
        "orgs": ["microsoft-research", "tsinghua-air"],
        "parents": ["openvla", "diffusion-policy"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2411.19650",
        "code": "https://github.com/microsoft/CogACT",
        "tags": ["componentized", "diffusion action module"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Argues the VLM should cognize and a separate diffusion module should act, then measures what that split buys.",
        "summary": "CogACT componentizes a VLA into a VLM cognition module and a specialized diffusion transformer action module conditioned on the VLM's output token, rather than making the VLM emit actions itself. The paper studies how action-module capacity scales given a fixed backbone and reports large gains over OpenVLA in both simulation and real manipulation with modest fine-tuning.",
        "innovation": [
            "Systematic study of action-module architecture and scaling with the VLM held fixed.",
            "Adaptive action ensembling across predicted chunks to smooth execution.",
        ],
        "matters": ["Gave empirical backing to the now-standard VLM-plus-action-expert factorization."],
        "limits": ["Evaluation leans on simulation benchmarks; real-robot breadth is narrow."],
        "lineage": "OpenVLA's backbone with Diffusion Policy's generative head, formalized as separate modules.",
    },
    {
        "id": "spatialvla",
        "name": "SpatialVLA",
        "cat": "vla",
        "year": 2025, "month": 1,
        "orgs": ["shanghai-ai-lab"],
        "parents": ["openvla"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2501.15830",
        "code": "https://github.com/SpatialVLA/SpatialVLA",
        "tags": ["3D position encoding", "adaptive action grids"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Injects explicit 3D structure into a VLA, because flat image tokens throw away the geometry manipulation needs.",
        "summary": "SpatialVLA adds Ego3D position encoding, fusing monocular depth estimates into the visual tokens, and replaces uniform action discretization with adaptive action grids fitted to the data distribution that can be re-fitted when transferring to a new robot. Trained on 1.1M real episodes, it reports better spatial generalization and faster cross-embodiment adaptation than uniformly tokenized VLAs.",
        "innovation": [
            "Ego3D position encoding gives 2D VLM tokens a 3D frame without extra sensors.",
            "Adaptive, re-fittable action grids as a transferable action representation across embodiments.",
        ],
        "matters": ["A leading example of the 3D-aware VLA direction addressing a core weakness of image-token policies."],
        "limits": ["Depends on monocular depth quality; gains are task-dependent."],
        "lineage": "OpenVLA-style architecture with 3D-aware inputs and a learned action discretization.",
    },
    {
        "id": "smolvla",
        "name": "SmolVLA",
        "cat": "vla",
        "year": 2025, "month": 6,
        "orgs": ["huggingface"],
        "parents": ["pi-0"],
        "influences": ["lerobot"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2506.01844",
        "code": "https://github.com/huggingface/lerobot",
        "tags": ["450M", "community data", "consumer GPU", "async inference"],
        "impact": 3,
        "confidence": "high",
        "tagline": "A 450M VLA trained only on community-contributed datasets that runs on a laptop.",
        "summary": "SmolVLA deliberately targets the low-resource end: a compact VLM backbone with a flow-matching action expert, trained exclusively on tens of thousands of public LeRobot community episodes rather than proprietary fleets. It skips layers in the backbone, interleaves attention, and ships an asynchronous inference stack that decouples perception from action execution to raise effective control rate on weak hardware.",
        "innovation": [
            "Showed a VLA trained purely on crowd-sourced, heterogeneous community data can be competitive at small scale.",
            "Asynchronous inference decoupling the perception and action loops for cheap hardware.",
        ],
        "matters": ["Radically lowered the entry cost for VLA experimentation, pairing with sub-$500 open-source arms."],
        "limits": ["Small capacity limits semantic generalization, and community data quality is uneven."],
        "lineage": "pi-0's flow-matching design compressed for consumer hardware inside the LeRobot ecosystem.",
    },
    {
        "id": "gr-1",
        "name": "GR-1",
        "cat": "vla",
        "year": 2023, "month": 12,
        "orgs": ["bytedance-seed"],
        "parents": ["transformer", "ego4d"],
        "influences": ["unipi", "r3m", "calvin"],
        "license": "code",
        "paper": "https://arxiv.org/abs/2312.13139",
        "code": "https://github.com/bytedance/GR-1",
        "tags": ["video pretraining", "GPT-style"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Pretrain on large-scale human video prediction, then fine-tune the same transformer to predict actions.",
        "summary": "GR-1 is a GPT-style transformer first pretrained on a large egocentric human video corpus to predict future frames given language, then fine-tuned on robot data to jointly predict future frames and actions. Video prediction acts as a physically grounded pretraining task, giving large gains on CALVIN's zero-shot generalization splits and on real-robot data efficiency.",
        "innovation": [
            "Video prediction as the pretraining objective for a manipulation policy, absorbing dynamics from human video.",
            "Joint frame-and-action prediction during fine-tuning, keeping the predictive signal alive.",
        ],
        "matters": ["A clean demonstration that human video, not only robot data, carries manipulation-relevant knowledge."],
        "limits": ["Video prediction is expensive and only loosely aligned with what control actually needs."],
        "lineage": "Transformer sequence modeling applied to video-then-action, anticipating world-model-based VLAs.",
    },
    {
        "id": "gr-2",
        "name": "GR-2",
        "cat": "vla",
        "year": 2024, "month": 10,
        "orgs": ["bytedance-seed"],
        "parents": ["gr-1"],
        "license": "closed",
        "site": "https://gr2-manipulation.github.io/",
        "tags": ["internet-scale video", "generalist"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "GR-1's recipe scaled to tens of millions of internet videos and 100+ real tasks.",
        "summary": "GR-2 scales video-generative pretraining to tens of millions of internet clips before robot fine-tuning, and adds a trajectory-conditioned video-prediction stage that effectively plans in pixel space before acting. Reported results span more than 100 tasks with strong multi-task and unseen-scene success rates.",
        "innovation": [
            "Internet-scale video generative pretraining directly serving a manipulation policy.",
            "Predict the video of the task first, then derive the actions that realize it.",
        ],
        "matters": ["Bridges video generation and control, the idea now central to world-model robotics."],
        "limits": ["Closed; results are author-reported only."],
        "lineage": "GR-1 scaled up with generative video planning added.",
    },
    {
        "id": "ecot",
        "name": "Embodied Chain-of-Thought",
        "cat": "vla",
        "year": 2024, "month": 7,
        "orgs": ["berkeley-rail"],
        "parents": ["openvla"],
        "influences": ["rt-2"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2407.08693",
        "code": "https://github.com/MichalZawalski/embodied-CoT",
        "tags": ["reasoning", "interpretable", "+28%"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Make the VLA write out plan, sub-task, object locations and gripper targets before acting; success jumps sharply.",
        "summary": "ECoT trains a VLA to emit a structured reasoning chain grounded in the scene (task restatement, sub-task, motion primitive, visible object bounding boxes, predicted gripper pixel position) before producing action tokens. Reasoning supervision is generated automatically by pipelines of off-the-shelf detectors and LLMs, and the resulting policy improves absolute success by roughly 28% over OpenVLA while exposing an inspectable trace a human can correct.",
        "innovation": [
            "Reasoning steps grounded in spatial predictions such as boxes and gripper pixels, not just free text.",
            "Fully automatic generation of reasoning supervision from existing robot data.",
            "Interpretability as a control surface: humans can read and edit the chain to fix behavior.",
        ],
        "matters": ["Imported chain-of-thought, the biggest LLM capability gain, into embodied control with real grounding."],
        "limits": ["Generating the chain costs inference time, cutting control rate substantially."],
        "lineage": "OpenVLA trained with automatically generated, spatially grounded reasoning traces.",
    },
    {
        "id": "rt-h",
        "name": "RT-H",
        "full_name": "Action Hierarchies Using Language",
        "cat": "vla",
        "year": 2024, "month": 3,
        "orgs": ["google-deepmind"],
        "parents": ["rt-2"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2403.01823",
        "tags": ["language motions", "correctable"],
        "impact": 2,
        "confidence": "high",
        "tagline": "Insert a layer of language motions ('move arm left', 'close gripper') between the task and the actuators.",
        "summary": "RT-H predicts an intermediate vocabulary of short language motions from the task and image, then predicts actions from that motion. Because the motions are shared across very different tasks, data transfers between them; and because they are human-readable, an operator can correct the motion in natural language and fold that correction back into training.",
        "innovation": [
            "A shared, human-readable mid-level action vocabulary enabling data sharing across dissimilar tasks.",
            "Language corrections as a cheap, natural interface for online policy repair.",
        ],
        "matters": ["An influential template for the hierarchical VLAs that followed, including pi-0.5 and Hi Robot."],
        "limits": ["The motion vocabulary is coarse; fine dexterous behavior does not decompose cleanly."],
        "lineage": "RT-2 with an explicit language-motion layer inserted into the action hierarchy.",
    },
]
