# -*- coding: utf-8 -*-
"""Seed data: Imitation Learning and generative policies."""

IL = [
    {
        "id": "alvinn",
        "name": "ALVINN",
        "full_name": "Autonomous Land Vehicle In a Neural Network",
        "cat": "il",
        "year": 1989,
        "orgs": ["cmu-ri"],
        "parents": [],
        "license": "closed",
        "paper": "https://proceedings.neurips.cc/paper/1988/hash/812b4ba287f5ee0bc9d43bbf5bbe87fb-Abstract.html",
        "tags": ["origin", "behavior cloning"],
        "impact": 3,
        "confidence": "high",
        "tagline": "The original end-to-end sensorimotor neural network: pixels in, steering out, 1989.",
        "summary": "Dean Pomerleau trained a three-layer network to map 30x32 camera images to steering direction, driving a vehicle on public roads. Every modern end-to-end policy descends from this, as does the field's oldest known failure mode: covariate shift, which Pomerleau already patched by synthetically generating off-center views, the ancestor of today's augmentation and DAgger.",
        "innovation": [
            "End-to-end learning from raw sensor input to control, with no hand-designed perception stack.",
            "Synthetic view generation to cover states the human demonstrator never visited.",
        ],
        "matters": ["Defines behavior cloning, the substrate under every VLA on this map."],
        "limits": ["Tiny capacity, no language, no generalization beyond the demonstrated conditions."],
        "lineage": "The root of the imitation-learning branch.",
    },
    {
        "id": "dagger",
        "name": "DAgger",
        "full_name": "Dataset Aggregation",
        "cat": "il",
        "year": 2011,
        "orgs": ["cmu-ri"],
        "parents": ["alvinn"],
        "license": "code",
        "paper": "https://arxiv.org/abs/1011.0686",
        "tags": ["covariate shift", "interactive expert", "no-regret"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The formal diagnosis and cure for imitation learning's compounding-error problem.",
        "summary": "Ross, Gordon and Bagnell showed that naive behavior cloning suffers errors compounding quadratically in the horizon, because the policy's own mistakes carry it to states the expert never demonstrated. DAgger fixes this by iteratively rolling out the learner, querying the expert for correct actions at the states the learner actually visits, and aggregating those labels, with no-regret guarantees that make error linear in horizon.",
        "innovation": [
            "Reduced imitation learning to online learning, yielding the first strong theoretical guarantee.",
            "Train on the learner's own state distribution, not the expert's: the field's most reused fix.",
        ],
        "matters": ["Every human-in-the-loop correction scheme, HIL-SERL and RECAP interventions included, is DAgger's descendant."],
        "limits": ["Requires an interactive expert able to label arbitrary states, which is expensive and often impossible."],
        "lineage": "The theoretical correction to naive behavior cloning as practiced since ALVINN.",
    },
    {
        "id": "gail",
        "name": "GAIL",
        "full_name": "Generative Adversarial Imitation Learning",
        "cat": "il",
        "year": 2016, "month": 6,
        "orgs": ["stanford-iris"],
        "parents": ["dagger"],
        "license": "code",
        "paper": "https://arxiv.org/abs/1606.03476",
        "tags": ["adversarial", "inverse RL"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Match the expert's state-action distribution with a discriminator instead of recovering a reward function.",
        "summary": "Ho and Ermon showed that inverse reinforcement learning followed by RL is equivalent to a distribution-matching problem, then solved it directly: a discriminator learns to separate agent from expert trajectories while the policy is trained by RL to fool it. This removed the expensive inner RL loop of classical IRL and scaled imitation to high-dimensional continuous control.",
        "innovation": [
            "Recast imitation as occupancy-measure matching, bypassing explicit reward recovery.",
            "Brought GAN machinery into robot learning.",
        ],
        "matters": ["Underpins reward-free imitation and many sim-to-real style-matching approaches."],
        "limits": ["Adversarial training is unstable and sample-hungry; largely displaced by direct generative policies."],
        "lineage": "A distribution-matching answer to the covariate-shift problem DAgger framed.",
    },
    {
        "id": "bc-z",
        "name": "BC-Z",
        "cat": "il",
        "year": 2021, "month": 12,
        "orgs": ["google-deepmind", "stanford-iris"],
        "parents": ["dagger"],
        "license": "code",
        "paper": "https://arxiv.org/abs/2202.02005",
        "tags": ["zero-shot task", "language or video conditioning", "100 tasks"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Task-conditioned behavior cloning at scale: 100 tasks, and generalization to tasks never demonstrated.",
        "summary": "BC-Z collected over 25k demonstrations across 100 manipulation tasks using an interactive DAgger-style correction loop, and conditioned a single policy on either a language embedding or a human video of the task. It achieved meaningful zero-shot success on held-out tasks, establishing that task conditioning plus data diversity, rather than architecture, was the lever for generalization.",
        "innovation": [
            "Task embeddings from language or video as the conditioning interface for a multi-task policy.",
            "Shared-autonomy collection where humans correct the policy live, scaling data cheaply.",
        ],
        "matters": ["The immediate methodological ancestor of RT-1 and the language-conditioned policy line."],
        "limits": ["Zero-shot success rates were modest; generalization was narrow semantic interpolation."],
        "lineage": "Scaled, task-conditioned behavior cloning with DAgger-style corrections.",
    },
    {
        "id": "implicit-bc",
        "name": "Implicit BC",
        "full_name": "Implicit Behavioral Cloning",
        "cat": "il",
        "year": 2021, "month": 9,
        "orgs": ["google-deepmind"],
        "parents": ["alvinn"],
        "license": "code",
        "paper": "https://arxiv.org/abs/2109.00137",
        "tags": ["energy-based", "multimodal actions"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Stop regressing the action and start scoring it. Energy-based policies express discontinuity that MSE cannot.",
        "summary": "Florence et al. replaced explicit action regression with an energy-based model that scores state-action pairs, selecting actions by optimization at inference. This addresses the core pathology of mean-squared-error behavior cloning: when expert behavior is multimodal, averaging the modes yields an action correct nowhere. Implicit BC solved precise contact-rich tasks that explicit policies failed outright.",
        "innovation": [
            "Energy-based policy formulation making multimodal and discontinuous behavior representable.",
            "Demonstrated the loss function, not capacity, was blocking precise manipulation.",
        ],
        "matters": ["Framed the multimodality problem that Diffusion Policy would later solve more practically."],
        "limits": ["Inference requires an optimization step over actions: slow and finicky to tune."],
        "lineage": "A direct critique and repair of the regression objective inherited from ALVINN-style cloning.",
    },
    {
        "id": "diffusion-policy",
        "name": "Diffusion Policy",
        "cat": "il",
        "year": 2023, "month": 3,
        "orgs": ["columbia-crl", "tri", "mit-csail"],
        "parents": ["implicit-bc"],
        "influences": ["act"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2303.04137",
        "code": "https://github.com/real-stanford/diffusion_policy",
        "tags": ["denoising", "action chunk", "receding horizon", "+46%"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Generate action sequences by denoising. The single most reused idea in modern manipulation.",
        "summary": "Diffusion Policy represents the visuomotor policy as a conditional denoising diffusion process over action sequences, reporting an average 46.9% improvement over prior methods across 15 tasks from 4 benchmarks. It expresses multimodal behavior gracefully, scales to high-dimensional action chunks, and trains stably, sidestepping both mode-averaging and Implicit BC's inference-time optimization.",
        "innovation": [
            "Diffusion over action chunks rather than single actions, giving temporal consistency and multimodality.",
            "Receding-horizon execution: predict a chunk, execute part of it, replan, closing the loop without jitter.",
            "Visual conditioning via FiLM with an end-to-end trained encoder, making it drop-in for real robots.",
        ],
        "matters": [
            "Became the default manipulation baseline worldwide, and the action head inside Octo, RDT-1B, GR00T and (as flow matching) pi-0.",
            "Made contact-rich, precise tasks learnable from roughly 50 to 200 demonstrations.",
        ],
        "limits": [
            "Iterative denoising costs inference time, later mitigated by flow matching and consistency distillation.",
            "Pure imitation, with no mechanism to exceed demonstration quality.",
        ],
        "lineage": "Achieves Implicit BC's multimodality goal with a generative diffusion model instead of energy minimization.",
    },
    {
        "id": "act",
        "name": "ACT / ALOHA",
        "full_name": "Action Chunking with Transformers",
        "cat": "il",
        "year": 2023, "month": 4,
        "orgs": ["stanford-iris"],
        "parents": ["transformer"],
        "influences": ["implicit-bc"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2304.13705",
        "code": "https://github.com/tonyzhaozh/aloha",
        "tags": ["action chunking", "CVAE", "low-cost bimanual", "50 demos"],
        "impact": 5,
        "confidence": "high",
        "tagline": "A cheap bimanual teleop rig plus action chunking: fine manipulation from 50 demonstrations.",
        "summary": "ALOHA is an open-source low-cost bimanual puppeteering setup; ACT is the policy trained on it. ACT predicts a chunk of about 100 future actions at once with a transformer CVAE, shortening the effective horizon and suppressing compounding error, while temporal ensembling across overlapping chunks smooths execution. Together they learn tasks like inserting a battery or opening a translucent condiment cup from roughly 50 demos at 80-90% success.",
        "innovation": [
            "Action chunking: predict k steps at once to cut the compounding-error horizon by a factor of k.",
            "Temporal ensembling of overlapping chunks for smooth, jitter-free real-time execution.",
            "Open, affordable bimanual hardware that democratized dexterous data collection.",
        ],
        "matters": [
            "Action chunking is now near-universal: pi-0, OpenVLA-OFT, GR00T and Diffusion Policy all use it.",
            "ALOHA hardware and its clones became the standard bimanual research platform.",
        ],
        "limits": ["Pure imitation from a fixed setup, with no language generalization and limited robustness to scene change."],
        "lineage": "Transformer sequence prediction applied to action chunks, on purpose-built cheap bimanual hardware.",
    },
    {
        "id": "mobile-aloha",
        "name": "Mobile ALOHA",
        "cat": "il",
        "year": 2024, "month": 1,
        "orgs": ["stanford-iris"],
        "parents": ["act"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2401.02117",
        "code": "https://github.com/MarkFzp/mobile-aloha",
        "tags": ["whole-body teleop", "mobile manipulation", "co-training"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Put ALOHA on a wheeled base, teleoperate the whole body, co-train with static data, get mobile manipulation from 50 demos.",
        "summary": "Mobile ALOHA adds a mobile base with whole-body teleoperation, letting one operator command base and both arms simultaneously. The headline result is empirical: co-training the mobile policy with the existing static ALOHA dataset lifts success by up to 90% on tasks with only 50 mobile demonstrations, covering cooking shrimp, calling and riding an elevator, and wiping spills.",
        "innovation": [
            "Whole-body teleoperation interface making mobile bimanual collection practical for one person.",
            "Static/mobile co-training as a data-efficiency multiplier.",
        ],
        "matters": ["Its widely shared demos shifted public and investor expectations of home robots."],
        "limits": ["Task-specific policies; each new task still needs its own demonstrations."],
        "lineage": "ACT extended to a mobile base with whole-body teleoperation.",
    },
    {
        "id": "aloha-unleashed",
        "name": "ALOHA Unleashed",
        "cat": "il",
        "year": 2024, "month": 10,
        "orgs": ["google-deepmind"],
        "parents": ["act", "diffusion-policy"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2410.13126",
        "tags": ["large demo counts", "shoelace tying", "diffusion"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Scale ALOHA-style collection far enough and diffusion policies learn to tie shoelaces and hang shirts.",
        "summary": "DeepMind scaled bimanual demonstration collection across a fleet of ALOHA 2 rigs and trained large transformer diffusion policies on tens of thousands of demonstrations per task family. The resulting policies handle deformables and high-precision dexterity, including tying shoelaces, hanging a shirt on a hanger and replacing a robot gear, that had resisted prior methods.",
        "innovation": [
            "Mapped the data-scaling curve for bimanual dexterity: hard deformable tasks become tractable with enough demos.",
            "Fleet-scale teleoperation infrastructure as the actual enabling technology.",
        ],
        "matters": ["Set the empirical bar for what pure imitation achieves given industrial-scale data."],
        "limits": ["Per-task data requirements are far beyond what most labs can collect."],
        "lineage": "ALOHA hardware plus diffusion policies at DeepMind data scale.",
    },
    {
        "id": "umi",
        "name": "UMI",
        "full_name": "Universal Manipulation Interface",
        "cat": "il",
        "year": 2024, "month": 2,
        "orgs": ["stanford-realab", "columbia-crl", "tri"],
        "parents": ["diffusion-policy"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2402.10329",
        "code": "https://github.com/real-stanford/universal_manipulation_interface",
        "tags": ["handheld gripper", "in-the-wild data", "action-cam"],
        "impact": 4,
        "confidence": "high",
        "tagline": "A cheap handheld gripper with an action camera: collect robot training data anywhere, with no robot.",
        "summary": "UMI is a hand-held parallel gripper with a wrist camera, fisheye side mirrors for implicit stereo, and IMU-aided visual-inertial odometry, letting anyone record demonstrations in any environment. Careful interface design plus latency matching between recording and policy inference means hand-collected data transfers to a real arm, enabling dynamic (tossing), bimanual, precise and long-horizon skills with zero robot time during collection.",
        "innovation": [
            "Decoupled data collection from robot hardware entirely: the demonstrator is the gripper.",
            "Explicit latency matching between human recording and robot execution so dynamic skills transfer.",
            "Side mirrors providing implicit stereo from one cheap camera.",
        ],
        "matters": ["Opened a path to in-the-wild manipulation data at internet scale; widely copied and extended."],
        "limits": ["Limited to one parallel-jaw morphology, with no force or torque sensing."],
        "lineage": "Data-collection hardware designed specifically to feed Diffusion Policy training.",
    },
    {
        "id": "vq-bet",
        "name": "VQ-BeT / Behavior Transformer",
        "cat": "il",
        "year": 2024, "month": 3,
        "orgs": ["nyu-grail"],
        "parents": ["transformer"],
        "influences": ["implicit-bc"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2403.03181",
        "code": "https://github.com/jayLEE0301/vq_bet_official",
        "tags": ["residual VQ", "faster than diffusion"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Tokenize continuous actions with residual vector quantization: multimodality without diffusion's inference cost.",
        "summary": "Behavior Transformer (2022) first showed a transformer with clustered action bins plus residual offsets could capture multimodal behavior. VQ-BeT replaces the clustering with hierarchical residual VQ-VAE action tokenization, giving a discrete latent action vocabulary a transformer predicts autoregressively then decodes to continuous actions, matching diffusion policy quality at several times faster inference.",
        "innovation": [
            "Residual vector quantization of action chunks into a hierarchical discrete vocabulary.",
            "Recovers multimodality in a single forward pass instead of an iterative denoising loop.",
        ],
        "matters": ["Anticipated the learned-action-tokenizer direction that FAST later pushed into large VLAs."],
        "limits": ["Quantization error caps precision, and the tokenizer must be retrained per action space."],
        "lineage": "Transformer policies with a learned discrete action codebook, as an alternative to diffusion.",
    },
    {
        "id": "dp3",
        "name": "3D Diffusion Policy (DP3)",
        "cat": "il",
        "year": 2024, "month": 3,
        "orgs": ["tsinghua-air", "stanford-svl"],
        "parents": ["diffusion-policy"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2403.03954",
        "code": "https://github.com/YanjieZe/3D-Diffusion-Policy",
        "tags": ["point cloud", "~10 demos", "dexterous hand"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Swap images for a sparse point cloud and diffusion policies learn dexterous tasks from about ten demonstrations.",
        "summary": "DP3 conditions a diffusion policy on a compact 3D point-cloud representation from an efficient encoder rather than on RGB images. Across 72 simulated and several real dexterous tasks it reports large gains in sample efficiency and much better generalization to novel viewpoints, objects and spatial arrangements, since geometry is invariant to the appearance changes that break image policies.",
        "innovation": [
            "Compact 3D visual representation as the conditioning signal for diffusion policies.",
            "Demonstrated dramatic sample-efficiency gains from geometry over appearance.",
        ],
        "matters": ["A leading argument for 3D-centric policies as image-based VLAs hit spatial generalization limits."],
        "limits": ["Needs calibrated depth; point clouds degrade badly on transparent and reflective objects."],
        "lineage": "Diffusion Policy with the image encoder replaced by a 3D point-cloud encoder.",
    },
    {
        "id": "lbm",
        "name": "Large Behavior Models",
        "cat": "il",
        "year": 2025, "month": 7,
        "orgs": ["tri", "boston-dynamics"],
        "parents": ["diffusion-policy"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2507.05331",
        "tags": ["statistical rigor", "blind A/B", "pretraining value"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "The field's most rigorous evaluation study: does multitask pretraining actually help? Yes, but less than headlines claim.",
        "summary": "TRI ran roughly 1,800 real-robot rollouts plus thousands of simulated ones under blind, randomized A/B protocols with proper statistical treatment, testing whether large multitask diffusion pretraining beats single-task baselines. It does: pretrained models need several times less task-specific data and improve steadily with pretraining scale. The study also documents how easily sloppy evaluation manufactures illusory gains.",
        "innovation": [
            "Blind, randomized, statistically powered real-robot evaluation methodology for manipulation.",
            "Separated the true value of multitask pretraining from evaluation noise.",
        ],
        "matters": ["A needed corrective in a field where most claims rest on a few dozen unblinded trials."],
        "limits": ["Closed models; the contribution is methodological rather than a released artifact."],
        "lineage": "Diffusion-policy-based multitask models, evaluated with unusual statistical discipline.",
    },
]
