# -*- coding: utf-8 -*-
"""Seed data: Human data and egocentric video.

The premise of this whole branch: teleoperated robot data tops out around 10^4
hours worldwide, while egocentric human video is 10^9 hours and growing. What
human video lacks is action labels. Every entry here is either a source of human
data or a method for closing that action-label gap.
"""

HUMAN = [
    {
        "id": "ego4d",
        "name": "Ego4D",
        "cat": "human-data",
        "year": 2021, "month": 10,
        "orgs": ["meta-fair", "cmu-ri"],
        "parents": [],
        "license": "open",
        "paper": "https://arxiv.org/abs/2110.07058",
        "site": "https://ego4d-data.org/",
        "tags": ["3670 hours", "9 countries", "dense narration", "no action labels"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Thousands of hours of daily life filmed from the wearer's own eyes — the corpus that made 'learn manipulation from human video' a real option.",
        "summary": "Ego4D is a massive-scale egocentric video dataset assembled by a consortium spanning nine countries: roughly 3,670 hours of unscripted daily activity recorded from head-mounted cameras by hundreds of unique participants, with dense timestamped narration and a suite of benchmark tasks. For robotics its value is not the benchmarks but the raw distribution it captures: human hands manipulating real objects in real homes and workplaces, at a scale no teleoperation fleet will ever reach.",
        "innovation": [
            "Scale and diversity of first-person manipulation footage, gathered by a coordinated multi-institution capture effort with a consent and de-identification protocol.",
            "Dense natural-language narration aligned to timestamps, giving the video language grounding for free.",
        ],
        "matters": [
            "The pretraining corpus behind R3M, GR-1 and most of the human-video branch.",
            "Reframed the data bottleneck as something potentially solvable without robot hardware.",
        ],
        "limits": [
            "No action labels, no robot embodiment, no force or tactile signal — closing that gap is the entire research problem.",
            "Passive observation only: no failures deliberately explored, no counterfactuals, no interventions.",
        ],
        "lineage": "The root of the human-data branch: the first corpus large enough to make action-free human video a credible pretraining source.",
    },
    {
        "id": "ego-exo4d",
        "name": "Ego-Exo4D",
        "cat": "human-data",
        "year": 2023, "month": 11,
        "orgs": ["meta-fair"],
        "parents": ["ego4d"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2311.18259",
        "site": "https://ego-exo4d-data.org/",
        "tags": ["paired ego + exo", "skilled activity", "3D pose"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Films the same skilled activity from the wearer's eyes and from outside simultaneously, so a model can learn to translate between the two.",
        "summary": "Ego-Exo4D captures synchronized egocentric and multiple exocentric camera views of people performing skilled activities — cooking, repair, sports, music — across many sites, with expert commentary and 3D body and hand annotation. The pairing matters for robots because a robot typically observes a scene from a third-person or wrist camera while human demonstration data is first-person, and the viewpoint mismatch quietly breaks naive transfer.",
        "innovation": [
            "Time-synchronized egocentric and exocentric capture at scale, giving direct supervision for cross-view translation.",
            "Expert commentary tracks as a supervision signal about how a task is being done well or badly.",
        ],
        "matters": ["Attacks the viewpoint mismatch that blocks direct reuse of human video by robot-mounted cameras."],
        "limits": ["Skilled-activity focus is narrower than everyday manipulation, and there are still no action labels."],
        "lineage": "Ego4D extended with paired third-person views and finer 3D annotation.",
    },
    {
        "id": "project-aria",
        "name": "Project Aria",
        "cat": "human-data",
        "year": 2023, "month": 7,
        "orgs": ["meta-fair"],
        "parents": ["ego4d"],
        "license": "code",
        "site": "https://www.projectaria.com/",
        "code": "https://github.com/facebookresearch/projectaria_tools",
        "tags": ["research glasses", "SLAM pose", "hand tracking", "eye tracking"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Research glasses that turn anyone wearing them into a calibrated robot-data collector.",
        "summary": "Project Aria is Meta's research eyewear platform: sensor-rich glasses with calibrated multi-camera capture, SLAM-grade 6-DoF pose, eye tracking and hand tracking, distributed to academic partners alongside open tooling and datasets. Its significance for manipulation is that it produces metric egocentric data — 3D hand trajectories in a known world frame — rather than raw pixels, and that is what makes a human recording convertible into a robot action target. A second-generation device followed in 2025.",
        "innovation": [
            "Calibrated, pose-grounded egocentric capture: hand trajectories arrive in metric 3D rather than needing to be estimated from video afterwards.",
            "Open tooling and data format, which made it the shared substrate for academic human-data robotics.",
        ],
        "matters": ["Turned human video from something you scrape into something you deliberately collect in a geometrically usable form. EgoMimic, EgoZero and much of the 2025 human-data work runs on it."],
        "limits": ["Limited hardware distribution; captures kinematics but no forces, and hand pose degrades under occlusion."],
        "lineage": "The capture instrument that made Ego4D's premise actionable for robot learning.",
    },
    {
        "id": "whirl",
        "name": "WHIRL",
        "full_name": "Human-to-Robot Imitation in the Wild",
        "cat": "human-data",
        "year": 2022, "month": 7,
        "orgs": ["cmu-ri"],
        "parents": [],
        "influences": ["ego4d"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2207.09450",
        "tags": ["one human video", "in the wild", "real-world practice"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Watch a person do the task once, extract a rough prior, then let the robot practise in the real world until it works.",
        "summary": "WHIRL observes a single human demonstration in an unstructured environment, uses hand and object tracking to build a prior over how the task should go, and then improves that prior through the robot's own real-world exploration. It ran across dozens of everyday tasks in real homes and offices — opening drawers, doors and fridges, taking out trash — with no task-specific robot demonstrations.",
        "innovation": [
            "Human video used as a prior for exploration rather than as a direct supervision target, which sidesteps exact retargeting.",
            "An agent that improves on hardware after watching, instead of requiring the human demonstration to be precisely imitable.",
        ],
        "matters": ["Showed one-shot human observation plus practice can beat large teleoperation datasets on in-the-wild tasks."],
        "limits": ["Needs real-world practice time for each new task, and the extracted priors are coarse."],
        "lineage": "The first practical human-video-to-robot pipeline that ran outside a lab.",
    },
    {
        "id": "mimicplay",
        "name": "MimicPlay",
        "cat": "human-data",
        "year": 2023, "month": 2,
        "orgs": ["stanford-svl", "nvidia-gear", "ut-austin-rpl"],
        "parents": [],
        "influences": ["whirl"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2302.12422",
        "code": "https://github.com/j96w/MimicPlay",
        "tags": ["human play data", "latent plans", "hierarchical"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Cheap human play video trains the high-level planner; a small amount of teleoperation trains the low-level controller.",
        "summary": "MimicPlay splits the problem by level. A high-level latent planner is learned from unstructured human play video — cheap, no robot, no action labels — to predict future hand trajectories, and a low-level policy conditioned on those plans is learned from a small number of robot teleoperation demonstrations. The split matches where each data source is actually strong: humans supply what to do next, the robot supplies how to do it.",
        "innovation": [
            "Assigns human video to the planning level and robot data to the control level, so the embodiment gap only has to be crossed once, coarsely.",
            "Latent plans over future hand trajectories as the interface between the two levels.",
        ],
        "matters": ["An influential template for the human/robot data division of labour that hierarchical VLAs later adopted."],
        "limits": ["Hand-trajectory plans carry no force or fine contact information, so precision tasks stay with the robot data."],
        "lineage": "WHIRL's human prior formalized as a learned high-level planner sitting over a robot low-level policy.",
    },
    {
        "id": "lapa",
        "name": "LAPA",
        "full_name": "Latent Action Pretraining from Videos",
        "cat": "human-data",
        "year": 2024, "month": 10,
        "orgs": ["uw", "microsoft-research", "nvidia-gear"],
        "parents": ["genie"],
        "influences": ["openvla"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2410.11758",
        "code": "https://github.com/LatentActionPretraining/LAPA",
        "tags": ["latent actions", "action-free video", "VQ-VAE", "3-stage"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Invent an action space from video that has no action labels, pretrain a VLA in it, then map it onto real robot actions.",
        "summary": "LAPA learns a discrete latent action vocabulary by training a VQ-VAE to explain the transition between consecutive video frames, pretrains a VLA to predict those latent actions from large-scale action-free video, then fine-tunes on a small amount of real robot data to map latents onto true actions. It reported matching or beating models pretrained on action-labelled robot data at a fraction of the pretraining cost.",
        "innovation": [
            "Quantized latent actions inferred from frame transitions as a direct substitute for missing action labels.",
            "The three-stage pipeline — latent action inference, latent pretraining, action fine-tuning — that has since become the standard shape of this approach.",
        ],
        "matters": [
            "The clearest demonstration that the action-label gap is bridgeable, which is what makes human video usable as VLA pretraining at all.",
            "The mechanism underneath GR00T N1's human-video layer and similar industrial data pyramids.",
        ],
        "limits": [
            "Latent actions encode visible change, so they capture nothing about force or stiffness.",
            "Quality degrades when the camera itself moves, which is exactly the egocentric case.",
        ],
        "lineage": "Genie's unsupervised latent action discovery redirected from generated worlds to robot policy pretraining.",
    },
    {
        "id": "egomimic",
        "name": "EgoMimic",
        "cat": "human-data",
        "year": 2024, "month": 10,
        "orgs": ["georgia-tech"],
        "parents": ["project-aria", "act"],
        "influences": ["mimicplay"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2410.24221",
        "code": "https://github.com/SimarKareer/EgoMimic",
        "tags": ["Aria glasses", "co-training", "human as embodiment"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Treat human data as just another embodiment and co-train on it — no retargeting stage, no separate planner.",
        "summary": "EgoMimic collects egocentric human demonstrations with Aria glasses, normalizes them into the same observation and action representation the robot uses (3D hand pose standing in for end-effector pose, with the human arm visually masked out), and simply co-trains one policy over both streams. Reported gains over robot-only training are large, and the human data is collected roughly an order of magnitude faster than teleoperation.",
        "innovation": [
            "Aligning human and robot data into a single shared action space so plain co-training works, with no explicit retargeting pipeline.",
            "Visual masking of the human arm to remove the morphology gap the policy would otherwise have to model.",
        ],
        "matters": ["The simplest recipe that works for mixing human and robot data, and it scales with cheap wearable capture rather than robot hours."],
        "limits": ["Requires the robot action space to be expressible as end-effector poses; in practice parallel-jaw grippers only."],
        "lineage": "MimicPlay's human/robot split collapsed into one co-trained policy over Aria-captured data.",
    },
    {
        "id": "egozero",
        "name": "EgoZero",
        "cat": "human-data",
        "year": 2025, "month": 5,
        "orgs": ["nyu-grail"],
        "parents": ["egomimic"],
        "influences": ["umi"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2505.20290",
        "tags": ["zero robot data", "Aria glasses", "point representation"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Train a manipulation policy from human demonstrations only — zero robot data — and deploy it.",
        "summary": "EgoZero takes the human-data idea to its limit: collect demonstrations with Aria glasses, extract a morphology-agnostic state and action representation built from 3D points rather than images or joint angles, train a policy on that alone, and deploy on a gripper robot that contributed nothing to training. Reported results cover several everyday manipulation tasks from a few minutes of human recording each.",
        "innovation": [
            "A point-based, morphology-agnostic state and action representation that erases the embodiment gap by construction rather than by learning around it.",
            "Transfer to a real robot with literally no robot training data.",
        ],
        "matters": ["If this scales it removes teleoperation from the pipeline entirely, which is the single largest cost in the field."],
        "limits": ["Small task set, short horizons and coarse precision; wholly dependent on accurate hand and object tracking."],
        "lineage": "EgoMimic's alignment idea pushed until robot data is no longer required at all.",
    },
    {
        "id": "egodex",
        "name": "EgoDex",
        "cat": "human-data",
        "year": 2025, "month": 5,
        "orgs": ["apple"],
        "parents": ["ego4d"],
        "influences": ["project-aria"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2505.11709",
        "tags": ["829 hours", "paired 3D hand pose", "194 tasks"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Hundreds of hours of egocentric dexterous manipulation with 3D hand and finger tracking already attached.",
        "summary": "EgoDex is a large egocentric dataset recorded on head-mounted consumer hardware with paired, automatically annotated 3D hand and finger poses across a wide range of everyday dexterous tasks. The annotation is the whole point: raw egocentric video has to pass through a hand-pose estimator before it can supervise anything, and bundling accurate poses at capture time removes the noisiest, most error-prone step in the human-to-robot pipeline.",
        "innovation": [
            "Pairing large-scale egocentric video with reliable 3D hand pose captured at recording time rather than estimated afterwards.",
            "Coverage of genuinely dexterous multi-finger tasks, not just parallel-jaw-style pick and place.",
        ],
        "matters": ["Dexterous hand data is the scarcest category in robot learning, and this is one of the largest open sources of it."],
        "limits": ["Human hand kinematics do not map cleanly onto most robot hands, and there is no force or tactile channel."],
        "lineage": "Ego4D-style capture carrying the hand-pose supervision that manipulation actually needs.",
    },
    {
        "id": "human-policy",
        "name": "Humanoid Policy ~ Human Policy (PH2D)",
        "cat": "human-data",
        "year": 2025, "month": 3,
        "orgs": ["ucsd-su", "mit-csail"],
        "parents": ["egomimic"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2503.13441",
        "tags": ["PH2D dataset", "humanoid", "co-training"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Collect human and humanoid data in one shared format and train a single policy over both — human data turns out to be nearly as valuable as robot data.",
        "summary": "This work collects a paired human-and-humanoid manipulation dataset (PH2D) through a shared capture protocol, then trains one human-humanoid action model across both. Because a humanoid's morphology is close to a human's, the alignment is far tighter than for arm-and-gripper platforms, and the paper reports that adding human data improves humanoid policies about as much as adding an equivalent quantity of teleoperated robot data.",
        "innovation": [
            "Exploits humanoid morphology to make human data near-substitutable for robot data, rather than merely a weak prior.",
            "A capture protocol producing directly comparable human and robot recordings, removing the alignment step.",
        ],
        "matters": ["The strongest data-side argument for humanoids: the form factor is what makes the world's human video usable as training data."],
        "limits": ["Hand and finger mismatch remains even when arms align, and the dataset is modest next to Ego4D-scale corpora."],
        "lineage": "EgoMimic's co-training applied where the embodiment gap is smallest — a body shaped like ours.",
    },
]
