# -*- coding: utf-8 -*-
"""Seed data: World Models, dreaming, and video-prediction-based planning."""

WM = [
    {
        "id": "world-models",
        "name": "World Models",
        "full_name": "World Models (Ha & Schmidhuber)",
        "cat": "world-model",
        "year": 2018, "month": 3,
        "orgs": ["google-deepmind"],
        "parents": [],
        "license": "code",
        "paper": "https://arxiv.org/abs/1803.10122",
        "tags": ["VAE + RNN", "training in dreams", "origin"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The paper that named the idea: compress the world into a latent model, then train the policy entirely inside it.",
        "summary": "A VAE compresses observations into a latent code, an RNN with a mixture-density head predicts the next latent given an action, and a tiny controller is evolved on top. The striking result was that the controller could be trained purely inside the learned dream, never touching the real environment, and still transfer back. This is the conceptual seed of every dreaming approach that followed.",
        "innovation": [
            "Explicit separation of vision (V), memory/dynamics (M) and controller (C) as trainable components.",
            "Training a policy entirely inside a learned generative model and transferring it to the real environment.",
        ],
        "matters": ["Defined 'dreaming' as a concrete engineering strategy rather than a metaphor."],
        "limits": ["Tiny scale, pixel-reconstruction bottleneck, and an evolutionary controller that does not scale."],
        "lineage": "The root of the world-model branch of robot learning.",
    },
    {
        "id": "planet",
        "name": "PlaNet",
        "full_name": "Deep Planning Network",
        "cat": "world-model",
        "year": 2018, "month": 11,
        "orgs": ["google-deepmind"],
        "parents": ["world-models"],
        "license": "code",
        "paper": "https://arxiv.org/abs/1811.04551",
        "tags": ["RSSM", "latent planning", "pixels"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Plan in a learned latent space instead of in pixels, with the recurrent state-space model that everything after it uses.",
        "summary": "PlaNet introduced the Recurrent State-Space Model, which splits latent state into a deterministic recurrent path and a stochastic path, capturing both reliable dynamics and genuine uncertainty. Planning runs entirely in latent space with the cross-entropy method, achieving performance comparable to model-free agents while using around 50 times less environment interaction.",
        "innovation": [
            "The RSSM latent dynamics architecture, still the backbone of the Dreamer line.",
            "Latent-space online planning that never renders a predicted image during control.",
        ],
        "matters": ["Made model-based RL from pixels competitive, which is the precondition for robot world models."],
        "limits": ["Online CEM planning at every step is computationally expensive and myopic beyond short horizons."],
        "lineage": "The World Models idea rebuilt with a principled latent dynamics model and planning instead of evolution.",
    },
    {
        "id": "dreamer",
        "name": "Dreamer",
        "cat": "world-model",
        "year": 2019, "month": 12,
        "orgs": ["google-deepmind"],
        "parents": ["planet"],
        "license": "code",
        "paper": "https://arxiv.org/abs/1912.01603",
        "tags": ["latent imagination", "actor-critic", "backprop through dynamics"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Stop planning at run time. Learn an actor and critic by backpropagating through thousands of imagined latent rollouts.",
        "summary": "Dreamer replaces PlaNet's expensive online search with policy learning inside the model: it rolls out imagined latent trajectories, computes value estimates along them, and backpropagates analytic gradients through the learned dynamics into the actor. This is far cheaper at deployment, handles long horizons, and set the template for all subsequent Dreamer versions.",
        "innovation": [
            "Analytic value gradients propagated through learned latent dynamics.",
            "Imagination as a training-time data amplifier rather than a run-time search procedure.",
        ],
        "matters": ["The dominant formulation of 'training in dreams' used across robotics and RL benchmarks."],
        "limits": ["Model bias compounds over imagined horizons; sensitive to reconstruction-based representation learning."],
        "lineage": "PlaNet's RSSM with actor-critic learning inside imagination replacing online planning.",
    },
    {
        "id": "dreamerv3",
        "name": "DreamerV3",
        "cat": "world-model",
        "year": 2023, "month": 1,
        "orgs": ["google-deepmind"],
        "parents": ["dreamer"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2301.04104",
        "code": "https://github.com/danijar/dreamerv3",
        "tags": ["one hyperparameter set", "150+ tasks", "Minecraft diamonds"],
        "impact": 5,
        "confidence": "high",
        "tagline": "One algorithm, one set of hyperparameters, more than 150 tasks, and the first agent to mine diamonds in Minecraft from scratch.",
        "summary": "DreamerV3 applies symlog prediction, two-hot value encoding, free bits and normalized returns to make the Dreamer recipe robust across radically different domains without per-task tuning. It masters continuous control, Atari, and open-world Minecraft with identical settings, and shows monotonically better performance and data efficiency as model size grows.",
        "innovation": [
            "A set of normalization and transformation tricks that make one hyperparameter configuration work everywhere.",
            "Demonstrated favorable scaling laws for world models: bigger model, better and more data-efficient.",
        ],
        "matters": ["Established world models as a general-purpose learning substrate, not a benchmark-specific trick."],
        "limits": ["Still reconstruction-based, which spends capacity modeling visually salient but task-irrelevant detail."],
        "lineage": "The Dreamer line hardened for robustness and scale.",
    },
    {
        "id": "daydreamer",
        "name": "DayDreamer",
        "cat": "world-model",
        "year": 2022, "month": 6,
        "orgs": ["berkeley-rail"],
        "parents": ["dreamer"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2206.14176",
        "code": "https://github.com/danijar/daydreamer",
        "tags": ["real robots", "no simulator", "1 hour walking"],
        "impact": 4,
        "confidence": "high",
        "tagline": "World models on physical robots with no simulator: a quadruped learns to walk from scratch in one hour.",
        "summary": "DayDreamer runs Dreamer directly on four physical robots, learning a world model online from real experience and training the policy inside imagination so that real interaction is used with maximum efficiency. A quadruped learned to walk in about an hour of real time, and robot arms learned visual pick-and-place, all without simulators or resets engineered per task.",
        "innovation": [
            "Demonstrated online world-model learning is fast enough for real hardware timescales.",
            "Removed the simulator from the loop entirely, and with it the sim-to-real gap.",
        ],
        "matters": ["The strongest evidence that dreaming is a practical real-robot method rather than a benchmark artifact."],
        "limits": ["Single-task, low-dimensional settings; nothing like VLA-level semantic generality."],
        "lineage": "Dreamer deployed directly on physical robots with online model learning.",
    },
    {
        "id": "muzero",
        "name": "MuZero",
        "cat": "world-model",
        "year": 2019, "month": 11,
        "orgs": ["google-deepmind"],
        "parents": ["world-models"],
        "license": "code",
        "paper": "https://arxiv.org/abs/1911.08265",
        "tags": ["value-equivalent model", "MCTS", "no rules given"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Learn only the parts of the world that matter for predicting value, then plan with tree search over that abstraction.",
        "summary": "MuZero learns a latent dynamics model trained purely to predict reward, value and policy, never to reconstruct observations, and plans with Monte Carlo tree search over that abstract model. It matched AlphaZero in Go, chess and shogi without being told the rules, and exceeded model-free methods on Atari. The value-equivalence principle it introduced is a direct answer to reconstruction-based world models wasting capacity.",
        "innovation": [
            "Value-equivalent model learning: model only what affects decisions, not what appears on screen.",
            "Unified learned models with tree search in high-dimensional visual domains.",
        ],
        "matters": ["The main intellectual alternative to reconstruction-based world models, echoed later by JEPA."],
        "limits": ["Tree search assumes discrete actions and cheap model queries, both awkward for continuous manipulation."],
        "lineage": "A decision-focused branch of world modeling, diverging from generative reconstruction.",
    },
    {
        "id": "td-mpc2",
        "name": "TD-MPC2",
        "cat": "world-model",
        "year": 2023, "month": 10,
        "orgs": ["ucsd-su", "meta-fair"],
        "parents": ["muzero", "planet"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2310.16828",
        "code": "https://github.com/nicklashansen/tdmpc2",
        "tags": ["implicit model", "104 tasks", "single agent"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Decoder-free latent model predictive control that scales to a single agent solving 104 continuous-control tasks.",
        "summary": "TD-MPC2 learns an implicit, decoder-free latent world model trained via temporal-difference losses, and plans with short-horizon model predictive control bootstrapped by a learned value function. A single 317M-parameter agent handles 104 tasks across four domains with multiple embodiments and action spaces, using one hyperparameter set.",
        "innovation": [
            "Decoder-free latent dynamics avoiding pixel reconstruction entirely.",
            "Hybrid short-horizon planning with terminal value bootstrapping, combining model-based and model-free strengths.",
        ],
        "matters": ["Shows value-equivalent world models scale to massively multitask continuous control."],
        "limits": ["Proprioceptive and simulation-centric; visual real-world manipulation is not its strong suit."],
        "lineage": "MuZero's value-equivalence idea adapted to continuous control with MPC instead of tree search.",
    },
    {
        "id": "unipi",
        "name": "UniPi",
        "full_name": "Learning Universal Policies via Text-Guided Video Generation",
        "cat": "world-model",
        "year": 2023, "month": 2,
        "orgs": ["google-deepmind", "mit-csail"],
        "parents": ["world-models"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2302.00111",
        "tags": ["video as plan", "inverse dynamics"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Generate a video of the task being done, then infer the actions that produce it.",
        "summary": "UniPi reframes policy learning as text-conditioned video generation: a diffusion model synthesizes a video of the robot completing the instruction, and a small inverse-dynamics model extracts the actions that realize those frames. Because video is a universal interface, the planner can absorb internet video and transfer across embodiments, with the action decoder being the only embodiment-specific part.",
        "innovation": [
            "Video as an embodiment-agnostic planning representation, decoupled from action decoding.",
            "Lets internet-scale video pretraining serve control directly.",
        ],
        "matters": ["Founded the video-generation-as-planning line running through GR-2, Genie and Cosmos-style systems."],
        "limits": ["Video generation is slow and physically inconsistent; hallucinated frames yield unexecutable plans."],
        "lineage": "World modeling in pixel space, with planning done by generation rather than search.",
    },
    {
        "id": "susie",
        "name": "SuSIE",
        "full_name": "Subgoal Synthesis via Image Editing",
        "cat": "world-model",
        "year": 2023, "month": 10,
        "orgs": ["berkeley-rail"],
        "parents": ["unipi"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2310.10639",
        "code": "https://github.com/kvablack/susie",
        "tags": ["image subgoals", "InstructPix2Pix"],
        "impact": 2,
        "confidence": "high",
        "tagline": "Have an image-editing model hallucinate the next subgoal image, then let a cheap policy chase it.",
        "summary": "SuSIE fine-tunes an instruction-guided image-editing diffusion model to produce a plausible near-future observation given the current image and a language command, then runs a low-level goal-reaching policy toward that image. Generating one subgoal image is far cheaper than a full video, and the image editor inherits broad semantic knowledge from internet pretraining.",
        "innovation": [
            "Single-image subgoal generation as a lightweight substitute for full video planning.",
            "Repurposes internet-pretrained image editors as high-level robot planners.",
        ],
        "matters": ["A practical middle ground between LLM planning and expensive generative video models."],
        "limits": ["Subgoal images can be physically impossible, and errors compound over long horizons."],
        "lineage": "UniPi's generative planning compressed from video to single-frame subgoals.",
    },
    {
        "id": "genie",
        "name": "Genie / Genie 3",
        "full_name": "Generative Interactive Environments",
        "cat": "world-model",
        "year": 2024, "month": 2,
        "orgs": ["google-deepmind"],
        "parents": ["world-models"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2402.15391",
        "tags": ["latent actions", "playable worlds", "unlabeled video"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Learns a latent action space from unlabeled internet video, producing worlds you can actually step through.",
        "summary": "Genie trains on 200,000+ hours of unlabeled internet gameplay video and infers a discrete latent action space with no action labels whatsoever, yielding a controllable generative environment where each latent action produces a consistent effect. Later generations extended this to real-time, longer-horizon interactive world generation with persistent scene memory.",
        "innovation": [
            "Unsupervised latent action discovery from pure video, removing the need for action-labeled data.",
            "Generated environments that are interactive and controllable rather than passive video.",
        ],
        "matters": ["The latent-action trick directly enabled robot models such as GR00T N1 to learn from unlabeled human video."],
        "limits": ["Closed; physical fidelity is far below what contact-rich manipulation requires. Verify version details."],
        "lineage": "World models trained from unlabeled video with self-discovered actions.",
    },
    {
        "id": "cosmos",
        "name": "NVIDIA Cosmos",
        "full_name": "World Foundation Model Platform for Physical AI",
        "cat": "world-model",
        "year": 2025, "month": 1,
        "orgs": ["nvidia-gear"],
        "parents": ["unipi", "genie"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2501.03575",
        "code": "https://github.com/NVIDIA/Cosmos",
        "tags": ["20M hours video", "open weights", "synthetic data engine"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Open world foundation models trained on tens of millions of hours of physical-world video, built as a data engine for robots.",
        "summary": "Cosmos packages diffusion and autoregressive world foundation models trained on roughly 20 million hours of driving and robotics video, plus tokenizers and a curation pipeline, under a permissive license. Its purpose is explicitly industrial: generate photorealistic, physically plausible synthetic trajectories to augment scarce real robot data, and provide a policy evaluator that does not require hardware.",
        "innovation": [
            "Open-weight world foundation models specifically targeted at physical AI rather than entertainment video.",
            "Positioned the world model as a synthetic-data factory and evaluation environment for policies.",
        ],
        "matters": ["Made world-model-generated training data a mainstream part of the robot-learning pipeline."],
        "limits": ["Visual plausibility outruns physical accuracy, especially for contact and deformation."],
        "lineage": "Video-generation world models industrialized as a data and evaluation platform.",
    },
    {
        "id": "v-jepa-2",
        "name": "V-JEPA 2",
        "cat": "world-model",
        "year": 2025, "month": 6,
        "orgs": ["meta-fair"],
        "parents": ["muzero"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2506.09985",
        "code": "https://github.com/facebookresearch/vjepa2",
        "tags": ["JEPA", "latent prediction", "62 hours robot data"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Predict in representation space, not pixels, then plan with the result using only tens of hours of robot data.",
        "summary": "V-JEPA 2 pretrains on over a million hours of internet video by predicting masked latent representations rather than reconstructing pixels. An action-conditioned variant is then fine-tuned on a relatively small amount of unlabeled robot interaction and used for zero-shot planning: given a goal image, it searches action sequences whose predicted latent outcome matches the goal, enabling pick-and-place with new objects in new environments without task-specific training.",
        "innovation": [
            "Joint-embedding predictive architecture applied to video, avoiding pixel reconstruction entirely.",
            "Zero-shot goal-conditioned planning from a world model trained mostly on passive internet video.",
        ],
        "matters": ["The leading non-generative alternative to video-diffusion world models, and far cheaper to run."],
        "limits": ["Demonstrated on short-horizon tasks; goal specification by image is restrictive. Verify current results."],
        "lineage": "Value-equivalent and latent-prediction thinking applied to large-scale video pretraining.",
    },
    {
        "id": "1x-world-model",
        "name": "1X World Model",
        "cat": "world-model",
        "year": 2024, "month": 11,
        "orgs": ["1x-technologies"],
        "parents": ["genie"],
        "license": "weights",
        "site": "https://www.1x.tech/discover/1x-world-model",
        "tags": ["policy evaluation", "humanoid", "challenge"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Use the world model as a test harness: evaluate humanoid policies in imagination instead of on hardware.",
        "summary": "1X trained an action-conditioned video world model on data from its humanoid fleet, aimed less at generating training data than at evaluating policies. Because real-robot evaluation is slow, dangerous and non-reproducible, simulating candidate policies inside a learned model of the robot's own environment gives a fast comparison signal. The team released data and ran a public challenge around the model.",
        "innovation": [
            "Framed world models primarily as an evaluation instrument for robot policies.",
            "Trained on proprietary humanoid interaction data rather than generic internet video.",
        ],
        "matters": ["Addresses evaluation, arguably the field's worst bottleneck, from an unusual angle."],
        "limits": ["A learned evaluator inherits its own model bias; agreement with real-world ranking is unproven."],
        "lineage": "Genie-style action-conditioned video models applied to humanoid policy evaluation.",
    },
    {
        "id": "dreamer4",
        "name": "Dreamer 4",
        "cat": "world-model",
        "year": 2025, "month": 9,
        "orgs": ["google-deepmind"],
        "parents": ["dreamerv3", "genie"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2509.24527",
        "tags": ["offline", "scalable world model", "Minecraft diamonds"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Train the agent entirely inside a scalable world model learned from offline data, with no environment interaction at all.",
        "summary": "Dreamer 4 learns a fast, accurate world model from a fixed offline dataset and trains the policy purely inside it, reporting the first agent to obtain diamonds in Minecraft without any environment interaction during learning. The emphasis is on world-model quality and inference speed sufficient for real-time imagination, which is the precondition for applying dreaming to robots where interaction is expensive.",
        "innovation": [
            "Offline-only agent training inside a learned model, removing environment interaction from the loop.",
            "Architectural work on making imagination fast enough for interactive-rate rollouts.",
        ],
        "matters": ["The most direct current answer to how robots might learn from logged data without hardware time."],
        "limits": ["Demonstrated in simulation and games; robot manipulation results are limited. Verify before citing."],
        "lineage": "The Dreamer line pushed toward fully offline training in scalable learned worlds.",
    },
]
