# -*- coding: utf-8 -*-
"""Seed data: Vision-Language-Action models, part 1 (the RT / open-generalist line).

confidence: "high" = author is confident in org/year/links; "medium" = verify next pass.
license: open = code+weights | weights = weights public, stack partly closed |
         code = code/data public, no policy weights | closed = proprietary
"""

VLA_1 = [
    {
        "id": "rt-1",
        "name": "RT-1",
        "full_name": "Robotics Transformer 1",
        "cat": "vla",
        "year": 2022, "month": 12,
        "orgs": ["google-deepmind"],
        "parents": ["transformer"],
        "influences": ["bc-z"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2212.06817",
        "code": "https://github.com/google-research/robotics_transformer",
        "tags": ["35M", "single-arm", "discrete tokens", "700 tasks"],
        "impact": 5,
        "confidence": "high",
        "tagline": "The first convincing demonstration that one transformer, given enough real robot data, absorbs hundreds of manipulation tasks.",
        "summary": "RT-1 trained a 35M-parameter transformer on ~130k teleoperated episodes covering 700+ tasks, collected over 17 months with a fleet of 13 Everyday Robots mobile manipulators. Images pass through an EfficientNet conditioned on the instruction via FiLM, a TokenLearner compresses each frame to 8 tokens, and the transformer emits discretized arm and base actions. It ran at 3 Hz on real hardware and kept improving as data scaled rather than saturating.",
        "innovation": [
            "Discretize continuous actions into 256 bins per dimension and predict them as tokens, turning control into next-token prediction.",
            "TokenLearner compression made a transformer policy fast enough (3 Hz) to close the loop on real hardware.",
            "Showed positive transfer from heterogeneous data: adding simulation and other robots' data raised real-world success instead of diluting it.",
        ],
        "matters": [
            "Established the 'scale real robot data + one transformer' recipe every later VLA inherits.",
            "Its 130k-episode dataset became a cornerstone of Open X-Embodiment.",
        ],
        "limits": [
            "No web-scale pretraining, so generalization to genuinely novel objects and phrasings was weak.",
            "Locked to one embodiment and a fixed low-frequency action space.",
        ],
        "lineage": "Applies the vanilla Transformer to robot control at fleet scale; directly extended by RT-2.",
    },
    {
        "id": "rt-2",
        "name": "RT-2",
        "full_name": "Vision-Language-Action Models Transfer Web Knowledge to Robotic Control",
        "cat": "vla",
        "year": 2023, "month": 7,
        "orgs": ["google-deepmind"],
        "parents": ["rt-1", "palm-e"],
        "influences": ["clip"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2307.15818",
        "tags": ["5B / 55B", "web co-training", "emergent semantics"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Coined 'VLA': fine-tune a web-scale vision-language model to emit robot actions as text tokens, and semantic knowledge transfers to control.",
        "summary": "RT-2 takes PaLI-X / PaLM-E backbones (5B to 55B) and co-fine-tunes them on internet vision-language data together with RT-1's robot trajectories, writing actions as strings of numbers that occupy otherwise-unused tokens in the text vocabulary. Because the same weights still answer visual questions, semantic knowledge leaks into control: the robot can pick 'the extinct animal' or 'something to use as a hammer' without ever having seen those instructions in robot data.",
        "innovation": [
            "Actions-as-text: no new output head, so web pretraining and robot fine-tuning share one objective.",
            "Co-fine-tuning (mixing web data into robot training) rather than sequential fine-tuning, which prevents forgetting semantics.",
            "A chain-of-thought variant that writes a plan in natural language before the action tokens.",
        ],
        "matters": [
            "Named and defined the VLA category that now dominates manipulation research.",
            "First robot policy that clearly knew things nobody had taught it on a robot.",
        ],
        "limits": [
            "Fully closed; the 55B model needed cloud inference at 1-3 Hz.",
            "New physical skills did not emerge, only new semantic recombinations of existing motions.",
        ],
        "lineage": "RT-1's data and action tokenization poured into a web-pretrained VLM backbone.",
    },
    {
        "id": "rt-x",
        "name": "RT-X (RT-1-X / RT-2-X)",
        "cat": "vla",
        "year": 2023, "month": 10,
        "orgs": ["google-deepmind", "berkeley-rail", "stanford-iris"],
        "parents": ["rt-1", "rt-2", "open-x-embodiment"],
        "license": "weights",
        "paper": "https://arxiv.org/abs/2310.08864",
        "code": "https://github.com/google-deepmind/open_x_embodiment",
        "tags": ["cross-embodiment", "22 robots"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Train one policy on 22 different robots at once and each robot beats its own specialist.",
        "summary": "Retraining the RT architectures on the pooled Open X-Embodiment corpus (60 datasets, 22 embodiments, 30+ labs) produced RT-1-X and RT-2-X. RT-1-X outperformed the original single-dataset specialist policies on 5 of 6 evaluated lab setups by roughly 50% on average, and RT-2-X showed skills that only appeared once other robots' data was in the mix.",
        "innovation": [
            "Demonstrated positive cross-embodiment transfer at scale: pooled training beat per-robot specialists.",
            "A shared end-effector action space that made wildly different arms trainable in one batch.",
        ],
        "matters": ["Justified the open-data pooling effort every open VLA now trains on."],
        "limits": ["Transfer benefits concentrated in low-data regimes; large in-domain datasets still won."],
        "lineage": "The RT architectures re-trained on the Open X-Embodiment pool.",
    },
    {
        "id": "octo",
        "name": "Octo",
        "cat": "vla",
        "year": 2024, "month": 5,
        "orgs": ["berkeley-rail", "stanford-iris", "cmu-ri"],
        "parents": ["open-x-embodiment", "diffusion-policy"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2405.12213",
        "code": "https://github.com/octo-models/octo",
        "tags": ["27M / 93M", "diffusion head", "flexible I/O"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The first genuinely open generalist policy designed to be fine-tuned: swap cameras, add proprioception, change the arm.",
        "summary": "Octo is a small transformer (27M and 93M variants) trained on 800k trajectories from Open X-Embodiment, with a diffusion action head producing continuous action chunks. Its defining property is a modular tokenizer layout: new observation streams (wrist cameras, joint states) or new action spaces attach at fine-tune time without touching pretrained weights, so a lab can adapt it on a single GPU in hours.",
        "innovation": [
            "Block-wise attention layout letting input and output modules be added or removed after pretraining.",
            "Diffusion head for continuous, multimodal action chunks instead of discretized tokens.",
            "Fully open weights, data mixture and training code.",
        ],
        "matters": ["Made generalist-policy research reproducible outside large industry labs."],
        "limits": ["No language-model backbone, so semantic generalization is far below RT-2 or OpenVLA."],
        "lineage": "Open X-Embodiment data plus Diffusion Policy's action head in a compact, adaptable transformer.",
    },
    {
        "id": "openvla",
        "name": "OpenVLA",
        "cat": "vla",
        "year": 2024, "month": 6,
        "orgs": ["stanford-iris", "berkeley-rail", "tri", "google-deepmind", "mit-csail"],
        "parents": ["rt-2", "open-x-embodiment"],
        "influences": ["octo"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2406.09246",
        "code": "https://github.com/openvla/openvla",
        "tags": ["7B", "LoRA", "DINOv2+SigLIP", "Llama 2"],
        "impact": 5,
        "confidence": "high",
        "tagline": "An open 7B VLA that beat the 55B RT-2-X and fine-tunes on a single consumer GPU.",
        "summary": "OpenVLA fine-tunes a Prismatic VLM (Llama 2 7B with a fused DINOv2 + SigLIP visual encoder) on 970k Open X-Embodiment episodes, predicting discretized action tokens. It outperformed RT-2-X (55B) by 16.5% absolute across 29 tasks while being far smaller, and the authors showed LoRA fine-tuning plus 4-bit quantization brings adaptation within reach of a single A100, or an RTX 4090 for inference.",
        "innovation": [
            "Fusing DINOv2 (spatial/geometric) with SigLIP (semantic) features, measurably better for control than either alone.",
            "Parameter-efficient LoRA adaptation of a large VLA to new robots at roughly 1% of full-tuning compute.",
            "Released everything: weights, data mixture, fine-tuning scripts, evaluation harness.",
        ],
        "matters": [
            "Became the default open VLA baseline; a large share of subsequent papers are OpenVLA variants.",
            "Proved open reproductions can exceed closed frontier robot models.",
        ],
        "limits": [
            "Single-image, single-arm, ~5 Hz autoregressive decoding, too slow for dynamic or bimanual work.",
            "Action discretization caps precision on fine-grained motion.",
        ],
        "lineage": "An open re-derivation of RT-2's recipe on Open X-Embodiment data with a Llama-2 backbone.",
    },
    {
        "id": "openvla-oft",
        "name": "OpenVLA-OFT",
        "full_name": "Optimized Fine-Tuning for Vision-Language-Action Models",
        "cat": "vla",
        "year": 2025, "month": 2,
        "orgs": ["stanford-iris"],
        "parents": ["openvla"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2502.19645",
        "code": "https://github.com/moojink/openvla-oft",
        "tags": ["parallel decoding", "~26x faster", "bimanual"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Three orthogonal fixes make OpenVLA roughly 26x faster and good enough for bimanual ALOHA.",
        "summary": "A systematic study of VLA fine-tuning design choices. Replacing autoregressive token-by-token decoding with a single parallel forward pass, predicting a whole action chunk at once, and regressing continuous actions with an L1 objective instead of classifying bins lifted throughput from ~5 Hz to over 100 Hz while raising success rates, including on bimanual tasks the original model could not perform.",
        "innovation": [
            "Parallel decoding of an entire action chunk in one forward pass, removing the autoregressive bottleneck.",
            "Continuous L1 regression head shown to match diffusion heads at a fraction of inference cost.",
            "FiLM language conditioning to stop the model ignoring instructions in multi-task settings.",
        ],
        "matters": ["Turned VLAs from demo-speed into control-rate systems; the recipe was widely adopted."],
        "limits": ["An adaptation recipe, not a new pretrained model, so it inherits OpenVLA's pretraining ceiling."],
        "lineage": "A direct engineering upgrade of OpenVLA's decoding and action representation.",
    },
    {
        "id": "pi-0",
        "name": "pi-0 (pi-zero)",
        "full_name": "A Vision-Language-Action Flow Model for General Robot Control",
        "cat": "vla",
        "year": 2024, "month": 10,
        "orgs": ["physical-intelligence"],
        "parents": ["rt-2", "diffusion-policy"],
        "influences": ["open-x-embodiment"],
        "license": "weights",
        "paper": "https://arxiv.org/abs/2410.24164",
        "code": "https://github.com/Physical-Intelligence/openpi",
        "tags": ["3B", "flow matching", "50 Hz", "PaliGemma"],
        "impact": 5,
        "confidence": "high",
        "tagline": "A flow-matching action expert bolted onto a VLM, running at 50 Hz. The first VLA that could fold laundry end to end.",
        "summary": "pi-0 pairs a PaliGemma 3B VLM with a separate ~300M action expert that generates action chunks via conditional flow matching, trained on roughly 10k hours across 7 robot configurations plus Open X-Embodiment. Continuous, high-frequency output unlocked genuinely dexterous long-horizon tasks (folding laundry from a dryer, bussing tables, assembling boxes) that token-based VLAs could not touch. Weights were released as openpi in early 2025.",
        "innovation": [
            "Flow matching for action generation: continuous, multimodal and high-frequency rather than discretized.",
            "A dedicated action expert with its own weights attending to VLM features, separating semantics from motor control.",
            "An explicit pretrain-then-post-train recipe borrowed from LLM practice, with curated post-training data.",
        ],
        "matters": [
            "Set the current architectural template: VLM backbone plus flow or diffusion action expert.",
            "openpi made a frontier-quality VLA openly available and is now a standard starting point.",
        ],
        "limits": ["Post-training data quality dominates results, and that data remains proprietary and expensive."],
        "lineage": "RT-2's VLM backbone idea with Diffusion Policy's continuous action generation, upgraded to flow matching.",
    },
    {
        "id": "pi-05",
        "name": "pi-0.5",
        "full_name": "A VLA with Open-World Generalization",
        "cat": "vla",
        "year": 2025, "month": 4,
        "orgs": ["physical-intelligence"],
        "parents": ["pi-0", "hi-robot"],
        "license": "weights",
        "paper": "https://arxiv.org/abs/2504.16054",
        "code": "https://github.com/Physical-Intelligence/openpi",
        "tags": ["open-world", "hierarchical", "heterogeneous co-training"],
        "impact": 5,
        "confidence": "high",
        "tagline": "Cleaning entire kitchens and bedrooms it has never seen: generalization moved from new objects to new buildings.",
        "summary": "pi-0.5 attacks open-world generalization by co-training on a deliberately heterogeneous mixture of multi-robot manipulation, high-level subtask annotations, web image-caption and VQA data, and verbal instructions from humans. At inference it first predicts a language subtask, then conditions the flow-matching action expert on it. The result cleans real, previously unseen homes for extended stretches.",
        "innovation": [
            "Discrete-then-continuous inference: predict the next subtask in language, then generate actions conditioned on it.",
            "Co-training across robot data, web data and human verbal coaching under one objective.",
            "Evidence that generalization scales with the number of distinct training environments, not just hours of data.",
        ],
        "matters": ["Reframed the bottleneck from motor skill to environmental diversity in the data."],
        "limits": ["Still brittle on tasks needing precise force control; recovery from bad states remains weak."],
        "lineage": "pi-0's architecture plus Hi Robot's hierarchical language decomposition, trained on far broader data.",
    },
    {
        "id": "pi-06",
        "name": "pi-*0.6 / RECAP",
        "cat": "vla",
        "year": 2025, "month": 11,
        "orgs": ["physical-intelligence"],
        "parents": ["pi-05"],
        "influences": ["hil-serl", "cql"],
        "license": "closed",
        "site": "https://www.physicalintelligence.company/blog",
        "tags": ["RL from experience", "advantage-conditioned", "self-improvement"],
        "impact": 4,
        "confidence": "medium",
        "tagline": "Let the VLA practice: RL on its own on-robot experience plus expert corrections roughly doubles throughput.",
        "summary": "RECAP (RL with Experience and Corrections via Advantage-conditioned Policies) post-trains a pi-0.6 VLA on its own deployment data. A value function trained on real rollouts scores each action's advantage, the policy is conditioned on that advantage so it can be steered toward high-value behavior at inference, and teleoperators intervene on failures to supply corrective data. Reported results include multi-hour espresso-machine operation and box assembly at around double the baseline throughput.",
        "innovation": [
            "Advantage-conditioned training folds RL value estimates into a generative VLA without unstable actor-critic loops.",
            "Treats teleoperator interventions as a first-class supervision channel, closing a deploy-correct-retrain loop.",
        ],
        "matters": ["A concrete answer to 'what comes after imitation' for large VLAs: learning from the robot's own experience."],
        "limits": ["Announced mainly via company blog and report; independent reproduction is limited. Verify before citing."],
        "lineage": "pi-0.6 post-trained with an RL procedure descended from offline RL and human-in-the-loop RL.",
    },
    {
        "id": "hi-robot",
        "name": "Hi Robot",
        "cat": "vla",
        "year": 2025, "month": 2,
        "orgs": ["physical-intelligence"],
        "parents": ["pi-0", "saycan"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2502.19417",
        "tags": ["hierarchical", "interactive", "System 1/2"],
        "impact": 3,
        "confidence": "high",
        "tagline": "A VLM inner monologue on top of a VLA, so you can interrupt the robot mid-task and it listens.",
        "summary": "Hi Robot places a high-level VLM reasoner above a pi-0 low-level policy. The reasoner decomposes complex prompts and real-time human feedback ('no, use the other one', 'that is not trash') into atomic language commands the VLA executes. Both levels are trained on robot data rather than hand-scripted, letting the system handle open-ended instructions and mid-execution corrections.",
        "innovation": [
            "Trains the high-level reasoner on robot-grounded data instead of using an off-the-shelf LLM planner.",
            "Handles real-time verbal interruption and correction during execution.",
        ],
        "matters": ["Made the System-1 / System-2 split concrete and learnable for manipulation."],
        "limits": ["Closed; latency between levels constrains how fast corrections take effect."],
        "lineage": "SayCan's hierarchical decomposition with both levels learned and grounded in robot data.",
    },
]
