# -*- coding: utf-8 -*-
"""Seed data: VLM / LLM planning, affordance grounding and code generation."""

VLM = [
    {
        "id": "saycan",
        "name": "SayCan",
        "full_name": "Do As I Can, Not As I Say",
        "cat": "vlm",
        "year": 2022, "month": 4,
        "orgs": ["google-deepmind"],
        "parents": ["bc-z"],
        "license": "code",
        "paper": "https://arxiv.org/abs/2204.01691",
        "code": "https://github.com/google-research/google-research/tree/master/saycan",
        "tags": ["affordance grounding", "LLM planner", "value functions"],
        "impact": 5,
        "confidence": "high",
        "tagline": "An LLM proposes what would help; learned value functions veto what the robot cannot actually do.",
        "summary": "SayCan scores each candidate skill by multiplying the LLM's likelihood that the skill is useful for the instruction (say) with a learned affordance value estimating whether it will succeed from the current state (can). The product selects the next skill, which grounds an ungrounded language model in the robot's real capabilities without any joint training. It executed long-horizon kitchen instructions like 'I spilled my drink, can you help?'.",
        "innovation": [
            "Multiplicative combination of semantic usefulness and learned physical feasibility.",
            "Made an off-the-shelf LLM usable as a robot planner with no robot-specific fine-tuning.",
        ],
        "matters": ["The founding work of LLM-driven robot planning; the ancestor of every hierarchical VLA."],
        "limits": ["Requires a fixed library of pretrained skills with value functions; cannot invent new behavior."],
        "lineage": "Language-model reasoning grounded through the learned skills of BC-Z-style policies.",
    },
    {
        "id": "inner-monologue",
        "name": "Inner Monologue",
        "cat": "vlm",
        "year": 2022, "month": 7,
        "orgs": ["google-deepmind"],
        "parents": ["saycan"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2207.05608",
        "tags": ["closed-loop feedback", "replanning"],
        "impact": 3,
        "confidence": "high",
        "tagline": "Feed success detectors, scene descriptions and human replies back into the LLM so it can notice failure and replan.",
        "summary": "Inner Monologue closes the loop around LLM planning by injecting textual feedback into the prompt: whether the last skill succeeded, what objects are currently visible, and what a human just said. The model then continues its chain of reasoning and revises the plan, producing retry behavior and adaptation to interruptions that open-loop planners cannot express.",
        "innovation": [
            "Textual feedback as the universal interface between perception, humans and the planner.",
            "Emergent replanning and retrying from prompting alone, with no additional training.",
        ],
        "matters": ["Established closed-loop LLM planning, the pattern later internalized by Hi Robot and pi-0.5."],
        "limits": ["Depends on reliable success detection, which remains an unsolved problem in itself."],
        "lineage": "SayCan made closed-loop by returning execution feedback to the language model.",
    },
    {
        "id": "code-as-policies",
        "name": "Code as Policies",
        "cat": "vlm",
        "year": 2022, "month": 9,
        "orgs": ["google-deepmind"],
        "parents": ["saycan"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2209.07753",
        "code": "https://github.com/google-research/google-research/tree/master/code_as_policies",
        "tags": ["program synthesis", "recursive", "perception APIs"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Let the LLM write the policy as Python: loops, conditionals and arithmetic over perception APIs.",
        "summary": "Rather than selecting from a skill list, the LLM writes executable code that calls perception and control APIs, recursively defining helper functions as needed. This gives the planner real expressive power: feedback loops, conditional logic, spatial arithmetic ('put the block 10 cm to the left'), and generalization to instructions no skill vocabulary anticipated.",
        "innovation": [
            "Programs as the policy representation, providing composition and control flow for free.",
            "Recursive function generation letting the model define undefined helpers on demand.",
        ],
        "matters": ["The template for LLM-as-orchestrator systems, including reward writers such as Eureka."],
        "limits": ["Only as good as the underlying perception and control APIs; generated code fails silently and unsafely."],
        "lineage": "SayCan's LLM planner upgraded from skill selection to program synthesis.",
    },
    {
        "id": "palm-e",
        "name": "PaLM-E",
        "full_name": "An Embodied Multimodal Language Model",
        "cat": "vlm",
        "year": 2023, "month": 3,
        "orgs": ["google-deepmind"],
        "parents": ["saycan", "clip"],
        "license": "closed",
        "paper": "https://arxiv.org/abs/2303.03378",
        "tags": ["562B", "multimodal tokens", "positive transfer"],
        "impact": 4,
        "confidence": "high",
        "tagline": "Inject images and robot states directly into an LLM's token stream, and web-scale reasoning transfers to embodied tasks.",
        "summary": "PaLM-E embeds continuous sensor modalities, images, 3D scene representations and robot states, into the same latent space as language tokens and trains a 562B model jointly across embodied and internet-scale vision-language tasks. Joint training produced positive transfer in both directions, and the resulting model plans robot behavior while remaining a strong general vision-language model.",
        "innovation": [
            "Continuous multimodal observations as first-class tokens inside a language model.",
            "Demonstrated positive transfer between internet-scale VL data and robot tasks in a single model.",
        ],
        "matters": ["The direct precursor to RT-2 and thus to the entire VLA architecture."],
        "limits": ["Enormous and closed; outputs high-level plans rather than actions."],
        "lineage": "SayCan's grounding problem solved by absorbing perception into the language model itself.",
    },
    {
        "id": "voxposer",
        "name": "VoxPoser",
        "cat": "vlm",
        "year": 2023, "month": 7,
        "orgs": ["stanford-svl"],
        "parents": ["code-as-policies"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2307.05973",
        "code": "https://github.com/huangwl18/VoxPoser",
        "tags": ["3D value maps", "zero-shot", "no training"],
        "impact": 4,
        "confidence": "high",
        "tagline": "The LLM writes code that paints 3D affordance and constraint maps, and a motion planner does the rest. No robot training data.",
        "summary": "VoxPoser has an LLM generate code that queries a vision-language model to compose 3D voxel value maps encoding where to go and what to avoid, then runs model predictive control against those maps to synthesize trajectories. The whole system is zero-shot: no robot demonstrations, no policy training, and it handles free-form instructions and open-set objects.",
        "innovation": [
            "3D value maps as the intermediate representation between language reasoning and motion planning.",
            "Composable, LLM-authored cost functions replacing learned policies entirely.",
        ],
        "matters": ["The strongest demonstration that foundation models plus classical planning can bypass robot data collection."],
        "limits": ["Limited to tasks expressible as trajectory optimization; no contact-rich or dexterous behavior."],
        "lineage": "Code as Policies extended so generated code composes spatial cost maps rather than calling fixed skills.",
    },
    {
        "id": "rekep",
        "name": "ReKep",
        "full_name": "Relational Keypoint Constraints",
        "cat": "vlm",
        "year": 2024, "month": 9,
        "orgs": ["stanford-svl"],
        "parents": ["voxposer"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2409.01652",
        "code": "https://github.com/huangwl18/ReKep",
        "tags": ["keypoint constraints", "bimanual", "real-time optimization"],
        "impact": 3,
        "confidence": "medium",
        "tagline": "Express manipulation as Python constraint functions over semantic keypoints, written by a VLM and solved in real time.",
        "summary": "ReKep represents a task as a sequence of relational constraints among 3D semantic keypoints, each a small Python function returning a cost. A VLM proposes the keypoints and writes the constraints from an image and instruction; a hierarchical solver then optimizes robot actions against them at roughly 10 Hz, supporting multi-stage, bimanual and reactive behaviors without task-specific training.",
        "innovation": [
            "Keypoint-relational constraints as a compact, optimizable and VLM-writable task specification.",
            "Real-time constrained optimization closing the loop against a foundation-model-authored objective.",
        ],
        "matters": ["Among the most capable training-free manipulation systems, and readable enough to debug."],
        "limits": ["Keypoint proposal quality bounds everything; fine force-controlled tasks remain out of reach."],
        "lineage": "VoxPoser's value maps replaced by sparser, more structured keypoint constraints.",
    },
    {
        "id": "moka",
        "name": "MOKA",
        "full_name": "Marking Open-vocabulary Keypoint Affordances",
        "cat": "vlm",
        "year": 2024, "month": 3,
        "orgs": ["berkeley-rail"],
        "parents": ["code-as-policies"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2403.03174",
        "tags": ["visual prompting", "affordance", "mark-based"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Draw candidate points on the image and ask the VLM to pick: turns motion generation into visual question answering.",
        "summary": "MOKA overlays candidate keypoints and waypoint marks onto the observation and prompts a VLM to select grasp points, target points and intermediate waypoints, converting continuous motion synthesis into a multiple-choice visual question the VLM is actually good at. The selected marks parameterize simple motion primitives, and successful rollouts can be distilled back into a policy.",
        "innovation": [
            "Visual mark-based prompting that sidesteps VLMs' weakness at emitting precise continuous coordinates.",
            "Uses successful zero-shot rollouts as demonstrations for subsequent policy distillation.",
        ],
        "matters": ["A widely copied trick for extracting spatial precision from models trained mostly on text."],
        "limits": ["Restricted to tasks decomposable into a few waypoints and primitives."],
        "lineage": "Foundation-model grounding via visual prompting rather than generated code.",
    },
    {
        "id": "molmo",
        "name": "Molmo (pointing)",
        "cat": "vlm",
        "year": 2024, "month": 9,
        "orgs": ["ai2"],
        "parents": ["clip"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2409.17146",
        "code": "https://github.com/allenai/molmo",
        "tags": ["pointing supervision", "open weights", "grounding"],
        "impact": 3,
        "confidence": "high",
        "tagline": "An open VLM trained to point at things, which turns out to be the interface robots needed.",
        "summary": "Molmo is trained on human-collected pointing annotations alongside dense captions, giving it the ability to answer spatial questions by emitting image coordinates rather than prose. That single capability makes it directly useful as a manipulation front-end: 'point at the handle you would grasp' is a query a robot can consume, and the weights and data are fully open.",
        "innovation": [
            "Pointing as a trained output modality, producing grounded coordinates instead of ambiguous text.",
            "Fully open model, data and training recipe at a time when competitive VLMs were closed.",
        ],
        "matters": ["Became a common open grounding module inside robot systems needing 'where', not just 'what'."],
        "limits": ["2D image points only, so depth and 3D pose must come from elsewhere."],
        "lineage": "CLIP-lineage vision-language modeling specialized toward spatial grounding for embodied use.",
    },
    {
        "id": "robopoint",
        "name": "RoboPoint",
        "cat": "vlm",
        "year": 2024, "month": 6,
        "orgs": ["uw", "nvidia-gear"],
        "parents": ["molmo"],
        "license": "open",
        "paper": "https://arxiv.org/abs/2406.10721",
        "code": "https://github.com/wentaoyuan/RoboPoint",
        "tags": ["spatial affordance", "synthetic instruction data"],
        "impact": 2,
        "confidence": "medium",
        "tagline": "Fine-tune a VLM on synthetic spatial instruction data so it predicts exactly where to place or grasp.",
        "summary": "RoboPoint generates synthetic instruction-following data with ground-truth spatial affordances from simulated scenes, then fine-tunes a VLM to output image keypoints satisfying relational instructions such as 'the free space to the left of the plate'. The result outperforms general VLMs on spatial affordance prediction and plugs directly into downstream motion planning.",
        "innovation": [
            "Automatic synthetic generation of spatial affordance supervision, avoiding manual annotation.",
            "Relational spatial language grounded to precise image coordinates.",
        ],
        "matters": ["Part of the shift toward VLMs that answer 'where exactly', which manipulation requires."],
        "limits": ["Synthetic-to-real gap in scene composition; predicts points, not full 6-DoF poses."],
        "lineage": "Pointing-style spatial grounding trained through targeted synthetic data.",
    },
]
